// Writes shared/beta3/<name>Wasm.ts from wasm/<name>.wasm for each name given (npm run build:wasm),
// so Node and the browser's workers load the kernels the same way, synchronously, without a separate file.
import fs from 'node:fs';
for (const name of process.argv.slice(2).length ? process.argv.slice(2) : ['blocks']) {
  const b = fs.readFileSync(new URL(`./${name}.wasm`, import.meta.url));
  fs.writeFileSync(
    new URL(`../shared/beta3/${name}Wasm.ts`, import.meta.url),
    `/** generated by \`npm run build:wasm\` from wasm/${name}.ts (AssemblyScript); do not edit */\nexport const ${name.toUpperCase()}_WASM = '${b.toString('base64')}';\n`,
  );
  console.log(`shared/beta3/${name}Wasm.ts: ${b.length} bytes`);
}
