/* Generated by server/beta3/pipeline/asim-configs.ts from ActivitySim's prototype_mtc configs; do not edit. */
export const ASIM = {
 "source": "ActivitySim prototype_mtc configs (github.com/ActivitySim/activitysim, activitysim/examples/prototype_mtc/configs, main branch, downloaded 2026-10-05), transferred by server/beta3/pipeline/asim-configs.ts",
 "cdap": {
  "indiv": [
   {
    "expr": "ptype == 1",
    "M": 1.378734579,
    "N": 0.622662391,
    "H": 0
   },
   {
    "expr": "ptype == 2",
    "M": -0.718823738,
    "N": 0.636032467,
    "H": 0
   },
   {
    "expr": "ptype == 3",
    "M": 2.353595176,
    "N": 0.609709846,
    "H": 0
   },
   {
    "expr": "ptype == 4",
    "M": -999,
    "N": 0.594645386,
    "H": 0
   },
   {
    "expr": "ptype == 5",
    "M": -999,
    "N": 0.408202071,
    "H": 0
   },
   {
    "expr": "ptype == 6",
    "M": 2.330918685,
    "N": -0.599119112,
    "H": 0
   },
   {
    "expr": "ptype == 7",
    "M": 3.295863529,
    "N": 0.57142434,
    "H": 0
   },
   {
    "expr": "(ptype == 7) & (age >= 6) & (age <= 9)",
    "M": -0.2943,
    "N": 0,
    "H": 0
   },
   {
    "expr": "(ptype == 7) & (age >= 13) & (age <= 15)",
    "M": -0.7141,
    "N": -0.672,
    "H": 0
   },
   {
    "expr": "ptype == 8",
    "M": 1.052531189,
    "N": -0.837567776,
    "H": 0
   },
   {
    "expr": "(ptype == 8) & (age >= 0) & (age <= 1)",
    "M": -0.4515,
    "N": 0,
    "H": 0
   },
   {
    "expr": "(ptype == 8) & (age >= 4) & (age <= 5)",
    "M": 0.6107,
    "N": 0,
    "H": 0
   },
   {
    "expr": "(ptype == 1) & (age < 40)",
    "M": 0.2091,
    "N": 0,
    "H": 0
   },
   {
    "expr": "(ptype == 5) & (age > 80)",
    "M": 0,
    "N": 0,
    "H": 0.7666
   },
   {
    "expr": "(ptype == 1) & (sex == 2)",
    "M": -0.1259,
    "N": 0,
    "H": 0
   },
   {
    "expr": "(ptype == 4) & (sex == 2)",
    "M": -0.743,
    "N": 0,
    "H": 0
   },
   {
    "expr": "(ptype == 5) & (sex == 2)",
    "M": 0.4769,
    "N": 0,
    "H": 0
   },
   {
    "expr": "(ptype == 4) & (auto_ownership > num_workers)",
    "M": 0.6515,
    "N": 0.8168,
    "H": 0
   },
   {
    "expr": "(ptype == 5) & (auto_ownership > num_workers)",
    "M": 2.992,
    "N": 1.056,
    "H": 0
   },
   {
    "expr": "(ptype == 8) & (auto_ownership > num_workers)",
    "M": 0,
    "N": 0.2991,
    "H": 0
   },
   {
    "expr": "(ptype == 1) & (auto_ownership < num_workers)",
    "M": 0,
    "N": 0,
    "H": 0.5039
   },
   {
    "expr": "(ptype == 4) & (auto_ownership < num_workers)",
    "M": 0,
    "N": 0,
    "H": 0.8965
   },
   {
    "expr": "(ptype == 5) & (auto_ownership < num_workers)",
    "M": 0,
    "N": 0,
    "H": 0.5496
   },
   {
    "expr": "(ptype == 6) & (auto_ownership < num_workers)",
    "M": 0,
    "N": 0,
    "H": 0.6475
   },
   {
    "expr": "(ptype == 7) & (auto_ownership < num_workers)",
    "M": 0,
    "N": 0,
    "H": 0.5862
   },
   {
    "expr": "(ptype == 8) & (auto_ownership < num_workers)",
    "M": 0,
    "N": 0,
    "H": 0.5061
   },
   {
    "expr": "(ptype == 1) & (income_in_thousands < 20)",
    "M": 0,
    "N": 0,
    "H": 0.5313
   },
   {
    "expr": "(ptype == 5) & (income_in_thousands < 20)",
    "M": 0,
    "N": 0,
    "H": 0.533
   },
   {
    "expr": "(ptype == 2) & (income_in_thousands < 20)",
    "M": 0,
    "N": 0,
    "H": 0.3232
   },
   {
    "expr": "(ptype == 2) & (income_in_thousands >= 50) & (income_in_thousands <= 100)",
    "M": 0,
    "N": 0,
    "H": -0.4032
   },
   {
    "expr": "(ptype == 2) & (income_in_thousands >= 100)",
    "M": 0,
    "N": 0.4207,
    "H": -0.3534
   },
   {
    "expr": "(ptype == 4) & (income_in_thousands >= 50) & (income_in_thousands <= 100)",
    "M": 0,
    "N": 0,
    "H": -0.5602
   },
   {
    "expr": "(ptype == 4) & (income_in_thousands >= 100)",
    "M": 0,
    "N": 0,
    "H": -0.7188
   },
   {
    "expr": "(ptype == 6) & (income_in_thousands < 20)",
    "M": 0,
    "N": 0,
    "H": 1.307
   },
   {
    "expr": "(ptype == 6) & (income_in_thousands >= 50) & (income_in_thousands <= 100)",
    "M": 0,
    "N": 0,
    "H": -0.5031
   },
   {
    "expr": "(ptype == 6) & (income_in_thousands >= 100)",
    "M": 0,
    "N": 0,
    "H": -2.046
   },
   {
    "expr": "(ptype == 8) & (income_in_thousands >= 50) & (income_in_thousands <= 100)",
    "M": 0,
    "N": 0,
    "H": -0.5708
   },
   {
    "expr": "(ptype == 8) & (income_in_thousands >= 100)",
    "M": 0,
    "N": 0,
    "H": -0.6186
   },
   {
    "expr": "(ptype == 1) * auPkTotal",
    "M": 0.1212,
    "N": 0,
    "H": 0
   },
   {
    "expr": "(ptype == 2) * auPkTotal",
    "M": 0.2004,
    "N": 0,
    "H": 0
   },
   {
    "expr": "(ptype == 4) * auPkTotal",
    "M": 0.2314,
    "N": 0,
    "H": 0
   },
   {
    "expr": "(ptype == 5) * auPkTotal",
    "M": 0.2792,
    "N": 0,
    "H": 0
   },
   {
    "expr": "(ptype == 4) * auOpRetail",
    "M": 0,
    "N": 0.07207,
    "H": 0
   },
   {
    "expr": "(ptype == 5) * auOpRetail",
    "M": 0,
    "N": 0.07207,
    "H": 0
   },
   {
    "expr": "(ptype == 3) * auOpRetail",
    "M": 0,
    "N": 0.07207,
    "H": 0
   },
   {
    "expr": "(ptype == 6) * auOpRetail",
    "M": 0,
    "N": 0.08233,
    "H": 0
   },
   {
    "expr": "(ptype == 7) * auOpRetail",
    "M": 0,
    "N": 0.08233,
    "H": 0
   },
   {
    "expr": "(ptype == 8) * auOpRetail",
    "M": 0,
    "N": 0.08233,
    "H": 0
   }
  ],
  "interaction": {
   "H11": 1.626,
   "H12": 0.7407,
   "H13": 1.183,
   "H14": 0.9436,
   "H15": 1.298,
   "H16": 2.064,
   "H17": 1.501,
   "H18": 0.9912,
   "H22": 0.8911,
   "H23": 1.642,
   "H24": 0.7057,
   "H25": 0.463,
   "H26": 3.057,
   "H27": 0.7685,
   "H28": 1.07,
   "H33": 1.018,
   "H34": 1.781,
   "H35": 0.4835,
   "H36": 1.546,
   "H37": 1.552,
   "H38": 1.34,
   "H44": 1.352,
   "H45": 1.209,
   "H46": 0.5243,
   "H47": 0.8112,
   "H48": 1.167,
   "H55": 1.407,
   "H56": 0.8632,
   "H57": 0.8632,
   "H58": 0.8632,
   "H66": 2.198,
   "H67": 0.977,
   "H68": 1.467,
   "H77": 2.8,
   "H78": 1.434,
   "H88": 1.378,
   "M11": 0.141,
   "M12": 0.08845,
   "M13": 0.4273,
   "M16": 0.3842,
   "M17": 0.2623,
   "M18": 0.5118,
   "M22": 1.135,
   "M23": 0.173,
   "M26": 1.103,
   "M27": 0.3079,
   "M28": 0.5074,
   "M33": 0.8726,
   "M36": -0.0021,
   "M37": 0.2975,
   "M38": 0.2254,
   "M66": 0.4794,
   "M67": 0.5151,
   "M68": 0.5516,
   "M77": 0.9731,
   "M78": 0.5961,
   "M88": 1.651,
   "N11": 1.123,
   "N12": 0.4947,
   "N13": 0.5523,
   "N14": 0.02186,
   "N15": 0.3115,
   "N16": 0.4095,
   "N17": 0.6008,
   "N18": 0.751,
   "N22": 1.032,
   "N23": 0.3355,
   "N24": 0.7477,
   "N25": 0.09831,
   "N26": 0.495,
   "N27": 0.8984,
   "N28": 1.452,
   "N33": 1.054,
   "N34": 0.193,
   "N35": 0.4065,
   "N36": 1.62,
   "N37": 0.5165,
   "N38": 0.8973,
   "N44": 0.6984,
   "N45": 0.1864,
   "N46": 0.6801,
   "N47": 0.5646,
   "N48": 1.164,
   "N55": 0.7291,
   "N56": 0.2919,
   "N57": 0.2919,
   "N58": 0.2919,
   "N66": 1.512,
   "N67": 1.422,
   "N68": 1.273,
   "N77": 1.553,
   "N78": 0.6184,
   "N88": 0.8771,
   "H124": 0.9573,
   "H122": 0.9573,
   "H144": 0.9573,
   "H126": 0.2939,
   "H146": 0.2939,
   "H222": 0.9881,
   "H224": 0.9881,
   "H244": 0.9881,
   "H226": 0.4374,
   "H246": 0.4374,
   "H446": 0.4374,
   "H266": 0.4747,
   "H466": 0.4747,
   "M111": 0.3133,
   "M112": 0.3495,
   "M114": 0.3495,
   "M666": -0.3906,
   "N112": 0.4637,
   "N114": 0.4637,
   "N124": 0.3491,
   "N122": 0.3491,
   "N144": 0.3491,
   "N166": 0.3553,
   "N222": -1.386,
   "N224": -1.386,
   "N444": -1.386,
   "N246": -0.8571,
   "N226": -0.8571,
   "N446": -0.8571,
   "M5": -999,
   "M4": -999,
   "M***": -0.0671,
   "N***": -0.3653,
   "H***": -1.181,
   "M****": -0.6104,
   "N****": -1.346,
   "H****": -3.733,
   "M*****": -1.528,
   "N*****": -3.453,
   "H*****": -8.621
  },
  "fixed": {
   "1": {
    "M": 0.79647,
    "N": 0.09368,
    "H": 0.10985
   },
   "2": {
    "M": 0.61678,
    "N": 0.25757,
    "H": 0.12565
   },
   "3": {
    "M": 0.69229,
    "N": 0.15641,
    "H": 0.1513
   },
   "4": {
    "M": 0,
    "N": 0.67169,
    "H": 0.32831
   },
   "5": {
    "M": 0,
    "N": 0.54295,
    "H": 0.45705
   },
   "6": {
    "M": 0.77609,
    "N": 0.06004,
    "H": 0.16387
   },
   "7": {
    "M": 0.68514,
    "N": 0.09144,
    "H": 0.22342
   },
   "8": {
    "M": 0.14056,
    "N": 0.06512,
    "H": 0.79432
   }
  }
 },
 "mtf": {
  "alts": [
   "work1",
   "work2",
   "school1",
   "school2",
   "work_and_school"
  ],
  "rows": [
   {
    "label": "util_ft_worker",
    "expr": "ptype == 1",
    "c": [
     0,
     -3.3781,
     0,
     0,
     0
    ]
   },
   {
    "label": "util_pt_worker",
    "expr": "ptype == 2",
    "c": [
     0,
     -3.0476,
     0,
     0,
     0
    ]
   },
   {
    "label": "util_univ",
    "expr": "ptype == 3",
    "c": [
     2.166,
     -1.3965,
     0,
     -3.7429,
     0.1073
    ]
   },
   {
    "label": "util_non_working_adult",
    "expr": "ptype == 4",
    "c": [
     0,
     0,
     0,
     0,
     0
    ]
   },
   {
    "label": "util_retired",
    "expr": "ptype == 5",
    "c": [
     0,
     0,
     0,
     0,
     0
    ]
   },
   {
    "label": "util_driving_age_child",
    "expr": "ptype == 6",
    "c": [
     0,
     0,
     0,
     -3.136,
     -4.4362
    ]
   },
   {
    "label": "util_pre_driving_age_child",
    "expr": "ptype == 7",
    "c": [
     0,
     0,
     0,
     -3.9703,
     0
    ]
   },
   {
    "label": "util_female_ft_worker",
    "expr": "(ptype == 1) & female",
    "c": [
     0,
     -0.2255,
     0.1592,
     0,
     -0.3442
    ]
   },
   {
    "label": "util_female_pt_worker",
    "expr": "(ptype == 2) & female",
    "c": [
     0,
     -0.2255,
     0.1592,
     0,
     -0.3442
    ]
   },
   {
    "label": "util_female_univ",
    "expr": "(ptype == 3) & female",
    "c": [
     0.1737,
     -0.2255,
     0.1592,
     0.114,
     -0.3442
    ]
   },
   {
    "label": "util_female_non_working_adult",
    "expr": "(ptype == 4) & female",
    "c": [
     0,
     -0.2255,
     0.1592,
     0,
     0
    ]
   },
   {
    "label": "util_female_retired",
    "expr": "(ptype == 5) & female",
    "c": [
     0,
     -0.2255,
     0.1592,
     0,
     0
    ]
   },
   {
    "label": "util_female_driving_age_child",
    "expr": "(ptype == 6) & female",
    "c": [
     0.1737,
     0,
     0,
     0.114,
     -0.3442
    ]
   },
   {
    "label": "util_female_pre_driving",
    "expr": "(ptype == 7) & female",
    "c": [
     0.1737,
     0,
     0,
     0.114,
     0
    ]
   },
   {
    "label": "util_under_35_ft",
    "expr": "(ptype == 1) & (age <= 35)",
    "c": [
     0,
     -0.1375,
     0.7218,
     0,
     0.9761
    ]
   },
   {
    "label": "util_under_35_pt",
    "expr": "(ptype == 2) & (age <= 35)",
    "c": [
     0,
     -0.1375,
     0.7218,
     0,
     0.9761
    ]
   },
   {
    "label": "util_under_35_univ",
    "expr": "(ptype == 3) & (age <= 35)",
    "c": [
     -0.4629,
     -0.1375,
     0,
     1.275,
     0.9761
    ]
   },
   {
    "label": "util_under_35_non_working",
    "expr": "(ptype == 4) & (age <= 35)",
    "c": [
     0,
     -0.1375,
     0.7218,
     0,
     0
    ]
   },
   {
    "label": "util_can_walk_to_work_ft",
    "expr": "(ptype == 1) & (distance_to_work < 3)",
    "c": [
     0,
     0.5268,
     0,
     0,
     0
    ]
   },
   {
    "label": "util_can_walk_to_work_pt",
    "expr": "(ptype == 2) & (distance_to_work < 3)",
    "c": [
     0,
     0.5268,
     0,
     0,
     0
    ]
   },
   {
    "label": "util_can_walk_to_work_univ",
    "expr": "(ptype == 3) & (distance_to_work < 3)",
    "c": [
     0,
     0.5268,
     0,
     0,
     0
    ]
   },
   {
    "label": "util_can_walk_to_work_non_working_adult",
    "expr": "(ptype == 4) & (distance_to_work < 3)",
    "c": [
     0,
     0.5268,
     0,
     0,
     0
    ]
   },
   {
    "label": "util_can_walk_to_work_retired",
    "expr": "(ptype == 5) & (distance_to_work < 3)",
    "c": [
     0,
     0.5268,
     0,
     0,
     0
    ]
   },
   {
    "label": "util_can_walk_to_school_univ",
    "expr": "(ptype == 3) & (distance_to_school < 3)",
    "c": [
     0,
     0,
     0,
     0.7114,
     0
    ]
   },
   {
    "label": "util_can_walk_to_school_driving_age_child",
    "expr": "(ptype == 6) & (distance_to_school < 3)",
    "c": [
     0,
     0,
     0,
     0.7114,
     0
    ]
   },
   {
    "label": "util_can_walk_to_school_pre_driving_age_child",
    "expr": "(ptype == 7) & (distance_to_school < 3)",
    "c": [
     0,
     0,
     0,
     0.7114,
     0
    ]
   },
   {
    "label": "util_can_walk_to_work_or_school_ft",
    "expr": "(ptype == 1) & ((distance_to_work < 3) | (distance_to_school < 3))",
    "c": [
     0,
     0,
     0,
     0,
     0.1391
    ]
   },
   {
    "label": "util_can_walk_to_work_or_school_pt",
    "expr": "(ptype == 2) & ((distance_to_work < 3) | (distance_to_school < 3))",
    "c": [
     0,
     0,
     0,
     0,
     0.1391
    ]
   },
   {
    "label": "util_can_walk_to_work_or_school_univ",
    "expr": "(ptype == 3) & ((distance_to_work < 3) | (distance_to_school < 3))",
    "c": [
     0,
     0,
     0,
     0,
     0.1391
    ]
   },
   {
    "label": "util_can_walk_to_work_or_school_driving_age_child",
    "expr": "(ptype == 6) & ((distance_to_work < 3) | (distance_to_school < 3))",
    "c": [
     0,
     0,
     0,
     0,
     0.1391
    ]
   },
   {
    "label": "util_round_trip_auto_time_to_work_ft",
    "expr": "(ptype == 1) * roundtrip_auto_time_to_work",
    "c": [
     0,
     -0.0035,
     0,
     0,
     -0.0034
    ]
   },
   {
    "label": "util_round_trip_auto_time_to_work_pt",
    "expr": "(ptype == 2) * roundtrip_auto_time_to_work",
    "c": [
     0,
     -0.0035,
     0,
     0,
     -0.0034
    ]
   },
   {
    "label": "util_round_trip_auto_time_to_work_univ",
    "expr": "(ptype == 3) * roundtrip_auto_time_to_work",
    "c": [
     0,
     -0.0035,
     0,
     0,
     -0.0034
    ]
   },
   {
    "label": "util_round_trip_auto_time_to_work_non_working_adult",
    "expr": "(ptype == 4) * roundtrip_auto_time_to_work",
    "c": [
     0,
     -0.0035,
     0,
     0,
     0
    ]
   },
   {
    "label": "util_round_trip_auto_time_to_work_retired",
    "expr": "(ptype == 5) * roundtrip_auto_time_to_work",
    "c": [
     0,
     -0.0035,
     0,
     0,
     0
    ]
   },
   {
    "label": "util_round_trip_auto_time_to_school_univ",
    "expr": "(ptype == 3) * roundtrip_auto_time_to_school",
    "c": [
     0,
     0,
     0,
     -0.0034,
     -0.0031
    ]
   },
   {
    "label": "util_round_trip_auto_time_to_school_driving_age_child",
    "expr": "(ptype == 6) * roundtrip_auto_time_to_school",
    "c": [
     0,
     0,
     0,
     -0.0034,
     -0.0031
    ]
   },
   {
    "label": "util_round_trip_auto_time_to_school_pre_driving_age_child",
    "expr": "(ptype == 7) * roundtrip_auto_time_to_school",
    "c": [
     0,
     0,
     0,
     -0.0034,
     0
    ]
   },
   {
    "label": "util_student_employted_univ",
    "expr": "(ptype == 3) & student_is_employed",
    "c": [
     3.014,
     3.014,
     0,
     0,
     3.014
    ]
   },
   {
    "label": "util_student_employted_driving_age_child",
    "expr": "(ptype == 6) & student_is_employed",
    "c": [
     3.014,
     3.014,
     0,
     0,
     3.014
    ]
   },
   {
    "label": "util_non_student_goes_to_school_ft",
    "expr": "(ptype == 1) & nonstudent_to_school",
    "c": [
     0,
     0,
     3.883,
     0,
     3.883
    ]
   },
   {
    "label": "util_non_student_goes_to_school_pt",
    "expr": "(ptype == 2) & nonstudent_to_school",
    "c": [
     0,
     0,
     3.883,
     0,
     3.883
    ]
   },
   {
    "label": "util_non_student_goes_to_school_non_working_adult",
    "expr": "(ptype == 4) & nonstudent_to_school",
    "c": [
     0,
     0,
     3.883,
     0,
     0
    ]
   },
   {
    "label": "util_non_student_goes_to_school_retired",
    "expr": "(ptype == 5) & nonstudent_to_school",
    "c": [
     0,
     0,
     3.883,
     0,
     0
    ]
   },
   {
    "label": "util_no_cars_in_hh_ft",
    "expr": "(ptype == 1) & (auto_ownership == 0)",
    "c": [
     0,
     -1.306,
     0,
     0,
     -1.302
    ]
   },
   {
    "label": "util_no_cars_in_hh_pt",
    "expr": "(ptype == 2) & (auto_ownership == 0)",
    "c": [
     0,
     -1.306,
     0,
     0,
     -1.302
    ]
   },
   {
    "label": "util_no_cars_in_hh_unif",
    "expr": "(ptype == 3) & (auto_ownership == 0)",
    "c": [
     0,
     -1.306,
     0,
     -1.413,
     -1.302
    ]
   },
   {
    "label": "util_no_cars_in_hh_non_working_adult",
    "expr": "(ptype == 4) & (auto_ownership == 0)",
    "c": [
     0,
     -1.306,
     0,
     0,
     0
    ]
   },
   {
    "label": "util_no_cars_in_hh_retired",
    "expr": "(ptype == 5) & (auto_ownership == 0)",
    "c": [
     0,
     -1.306,
     0,
     0,
     0
    ]
   },
   {
    "label": "util_no_cars_in_hh_driving_age_student",
    "expr": "(ptype == 6) & (auto_ownership == 0)",
    "c": [
     0,
     0,
     0,
     -1.413,
     -1.302
    ]
   },
   {
    "label": "util_no_cars_in_hh_pre_driving_age",
    "expr": "(ptype == 7) & (auto_ownership == 0)",
    "c": [
     0,
     0,
     0,
     -1.413,
     0
    ]
   },
   {
    "label": "util_fewer_cars_than_drivers_univ",
    "expr": "(ptype == 3) & (auto_ownership < num_drivers)",
    "c": [
     0,
     0,
     0,
     -0.5759,
     0
    ]
   },
   {
    "label": "util_fewer_cars_than_drivers_driving_age_student",
    "expr": "(ptype == 6) & (auto_ownership < num_drivers)",
    "c": [
     0,
     0,
     0,
     -0.5759,
     0
    ]
   },
   {
    "label": "util_fewer_cars_than_drivers_pre_driving_age",
    "expr": "(ptype == 7) & (auto_ownership < num_drivers)",
    "c": [
     0,
     0,
     0,
     -0.5759,
     0
    ]
   },
   {
    "label": "util_num_preschool_in_hh_ft",
    "expr": "(ptype == 1) * (num_young_children)",
    "c": [
     0,
     -0.1478,
     -0.1335,
     0,
     -0.1251
    ]
   },
   {
    "label": "util_num_preschool_in_hh_pt",
    "expr": "(ptype == 2) * (num_young_children)",
    "c": [
     0,
     -0.1478,
     -0.1335,
     0,
     -0.1251
    ]
   },
   {
    "label": "util_num_preschool_in_hh_univ",
    "expr": "(ptype == 3) * (num_young_children)",
    "c": [
     0.2191,
     -0.1478,
     0,
     -0.5577,
     -0.1251
    ]
   },
   {
    "label": "util_num_preschool_in_hh_non_working_adult",
    "expr": "(ptype == 4) * (num_young_children)",
    "c": [
     0,
     -0.1478,
     -0.1335,
     0,
     0
    ]
   },
   {
    "label": "util_num_preschool_in_hh_retired",
    "expr": "(ptype == 5) * (num_young_children)",
    "c": [
     0,
     -0.1478,
     -0.1335,
     0,
     0
    ]
   },
   {
    "label": "util_num_preschool_in_hh_driving_age_student",
    "expr": "(ptype == 6) * (num_young_children)",
    "c": [
     0.2191,
     0,
     0,
     -0.5577,
     -0.1251
    ]
   },
   {
    "label": "util_num_preschool_in_hh_pre_driving_age_in_school",
    "expr": "(ptype == 7) * (num_young_children)",
    "c": [
     0.2191,
     0,
     0,
     -0.5577,
     0
    ]
   },
   {
    "label": "util_num_nonworkers_in_hh_ft",
    "expr": "(ptype == 1) * num_non_workers",
    "c": [
     0,
     0,
     0.2574,
     0,
     0
    ]
   },
   {
    "label": "util_num_nonworkers_in_hh_pt",
    "expr": "(ptype == 2) * num_non_workers",
    "c": [
     0,
     0,
     0.2574,
     0,
     0
    ]
   },
   {
    "label": "util_hh_income_gt_50k_ft",
    "expr": "(ptype == 1) & (income_in_thousands > 50)",
    "c": [
     0,
     0,
     0.0347,
     0,
     0.0347
    ]
   },
   {
    "label": "util_hh_income_gt_50k_pt",
    "expr": "(ptype == 2) & (income_in_thousands > 50)",
    "c": [
     0,
     0,
     0.0347,
     0,
     0.0347
    ]
   },
   {
    "label": "util_hh_income_gt_50k_univ",
    "expr": "(ptype == 3) & (income_in_thousands > 50)",
    "c": [
     -0.0528,
     -0.0528,
     0,
     0,
     -0.0528
    ]
   },
   {
    "label": "util_hh_income_gt_50k_non_working_adult",
    "expr": "(ptype == 4) & (income_in_thousands > 50)",
    "c": [
     0,
     0,
     0.0347,
     0,
     0
    ]
   },
   {
    "label": "util_hh_income_gt_50k_retired",
    "expr": "(ptype == 5) & (income_in_thousands > 50)",
    "c": [
     0,
     0,
     0.0347,
     0,
     0
    ]
   },
   {
    "label": "util_hh_income_gt_50k_driving_age_student",
    "expr": "(ptype == 6) & (income_in_thousands > 50)",
    "c": [
     -0.0528,
     0,
     0,
     0,
     -0.0528
    ]
   },
   {
    "label": "util_hh_income_gt_50k_pre_driving_age_student",
    "expr": "(ptype == 7) & (income_in_thousands > 50)",
    "c": [
     -0.0528,
     0,
     0,
     0,
     0
    ]
   },
   {
    "label": "util_non_family_hh_ft",
    "expr": "(ptype == 1) & non_family",
    "c": [
     0,
     0,
     -0.25,
     0,
     -0.25
    ]
   },
   {
    "label": "util_non_family_hh_pt",
    "expr": "(ptype == 2) & non_family",
    "c": [
     0,
     0,
     -0.25,
     0,
     -0.25
    ]
   },
   {
    "label": "util_non_family_hh_univ",
    "expr": "(ptype == 3) & non_family",
    "c": [
     -0.1792,
     -0.1792,
     0,
     0,
     -0.1792
    ]
   },
   {
    "label": "util_non_family_hh_non_working_adult",
    "expr": "(ptype == 4) & non_family",
    "c": [
     0,
     0,
     -0.25,
     0,
     0
    ]
   },
   {
    "label": "util_non_family_hh_retired",
    "expr": "(ptype == 5) & non_family",
    "c": [
     0,
     0,
     -0.25,
     0,
     0
    ]
   },
   {
    "label": "util_non_family_hh_driving_age_student",
    "expr": "(ptype == 6) & non_family",
    "c": [
     -0.1792,
     0,
     0,
     0,
     -0.1792
    ]
   },
   {
    "label": "util_non_family_hh_pre_driving_age_student",
    "expr": "(ptype == 7) & non_family",
    "c": [
     -0.1792,
     0,
     0,
     0,
     0
    ]
   },
   {
    "label": "util_num_under_16_not_at_school_ft",
    "expr": "(ptype == 1) * num_under16_not_at_school",
    "c": [
     0,
     0.1804,
     0,
     0,
     -0.1955
    ]
   },
   {
    "label": "util_num_under_16_not_at_school_pt",
    "expr": "(ptype == 2) * num_under16_not_at_school",
    "c": [
     0,
     0.1804,
     0,
     0,
     -0.1955
    ]
   },
   {
    "label": "util_num_under_16_not_at_school_univ",
    "expr": "(ptype == 3) * num_under16_not_at_school",
    "c": [
     0,
     0.1804,
     0,
     0.0866,
     -0.1955
    ]
   },
   {
    "label": "util_num_under_16_not_at_school_non_working_adult",
    "expr": "(ptype == 4) * num_under16_not_at_school",
    "c": [
     0,
     0.1804,
     0,
     0,
     0
    ]
   },
   {
    "label": "util_num_under_16_not_at_school_retired",
    "expr": "(ptype == 5) * num_under16_not_at_school",
    "c": [
     0,
     0.1804,
     0,
     0,
     0
    ]
   },
   {
    "label": "util_num_under_16_not_at_school_driving_age_student",
    "expr": "(ptype == 6) * num_under16_not_at_school",
    "c": [
     0,
     0,
     0,
     0.0866,
     -0.1955
    ]
   },
   {
    "label": "util_num_under_16_not_at_school_pre_driving_age",
    "expr": "(ptype == 7) * num_under16_not_at_school",
    "c": [
     0,
     0,
     0,
     0.0866,
     0
    ]
   },
   {
    "label": "util_nome_urban_ft",
    "expr": "(ptype == 1) & home_is_urban",
    "c": [
     0,
     0.2308,
     -0.1361,
     0,
     -0.3509
    ]
   },
   {
    "label": "util_nome_urban_pt",
    "expr": "(ptype == 2) & home_is_urban",
    "c": [
     0,
     0.2308,
     -0.1361,
     0,
     -0.3509
    ]
   },
   {
    "label": "util_nome_urban_univ",
    "expr": "(ptype == 3) & home_is_urban",
    "c": [
     -0.2831,
     0.2308,
     0,
     0.317,
     -0.3509
    ]
   },
   {
    "label": "util_nome_urban_non_working_adult",
    "expr": "(ptype == 4) & home_is_urban",
    "c": [
     0,
     0.2308,
     -0.1361,
     0,
     0
    ]
   },
   {
    "label": "util_nome_urban_retired",
    "expr": "(ptype == 5) & home_is_urban",
    "c": [
     0,
     0.2308,
     -0.1361,
     0,
     0
    ]
   },
   {
    "label": "util_nome_urban_driving_age_student",
    "expr": "(ptype == 6) & home_is_urban",
    "c": [
     -0.2831,
     0,
     0,
     0.317,
     -0.3509
    ]
   },
   {
    "label": "util_nome_urban_pre_driving_age_student",
    "expr": "(ptype == 7) & home_is_urban",
    "c": [
     -0.2831,
     0,
     0,
     0.317,
     0
    ]
   },
   {
    "label": "util_availability_ft",
    "expr": "ptype == 1",
    "c": [
     0,
     0,
     0,
     -999,
     0
    ]
   },
   {
    "label": "util_availability_pt",
    "expr": "ptype == 2",
    "c": [
     0,
     0,
     0,
     -999,
     0
    ]
   },
   {
    "label": "util_availability_non_working_adult",
    "expr": "ptype == 4",
    "c": [
     0,
     0,
     0,
     -999,
     -999
    ]
   },
   {
    "label": "util_availability_retired",
    "expr": "ptype == 5",
    "c": [
     0,
     0,
     0,
     -999,
     -999
    ]
   },
   {
    "label": "util_availability_driving_age_child",
    "expr": "ptype == 6",
    "c": [
     -999,
     -999,
     0,
     0,
     0
    ]
   },
   {
    "label": "util_availability_pre_driving_age_student",
    "expr": "ptype == 7",
    "c": [
     0,
     -999,
     0,
     0,
     -999
    ]
   },
   {
    "label": "util_availability_pre_driving_age_not_in_school",
    "expr": "ptype == 8",
    "c": [
     -999,
     -999,
     0,
     -999,
     -999
    ]
   },
   {
    "label": "util_availability_work_tours_no_usual_work_location",
    "expr": "~(workplace_zone_id > -1)",
    "c": [
     -999,
     -999,
     0,
     0,
     -999
    ]
   },
   {
    "label": "util_availability_school_tours_no_usual_school_location",
    "expr": "~(school_zone_id > -1)",
    "c": [
     0,
     0,
     -999,
     -999,
     -999
    ]
   }
  ]
 },
 "nmtf": {
  "purposes": [
   "escort",
   "shopping",
   "othmaint",
   "othdiscr",
   "eatout",
   "social"
  ],
  "alts": [
   [
    0,
    0,
    0,
    0,
    0,
    0
   ],
   [
    0,
    0,
    0,
    1,
    0,
    0
   ],
   [
    0,
    0,
    0,
    0,
    0,
    1
   ],
   [
    0,
    0,
    0,
    1,
    0,
    1
   ],
   [
    0,
    0,
    0,
    0,
    1,
    0
   ],
   [
    0,
    0,
    0,
    1,
    1,
    0
   ],
   [
    0,
    0,
    0,
    0,
    1,
    1
   ],
   [
    0,
    0,
    0,
    1,
    1,
    1
   ],
   [
    0,
    0,
    1,
    0,
    0,
    0
   ],
   [
    0,
    0,
    1,
    1,
    0,
    0
   ],
   [
    0,
    0,
    1,
    0,
    0,
    1
   ],
   [
    0,
    0,
    1,
    1,
    0,
    1
   ],
   [
    0,
    0,
    1,
    0,
    1,
    0
   ],
   [
    0,
    0,
    1,
    1,
    1,
    0
   ],
   [
    0,
    0,
    1,
    0,
    1,
    1
   ],
   [
    0,
    0,
    1,
    1,
    1,
    1
   ],
   [
    0,
    1,
    0,
    0,
    0,
    0
   ],
   [
    0,
    1,
    0,
    1,
    0,
    0
   ],
   [
    0,
    1,
    0,
    0,
    0,
    1
   ],
   [
    0,
    1,
    0,
    1,
    0,
    1
   ],
   [
    0,
    1,
    0,
    0,
    1,
    0
   ],
   [
    0,
    1,
    0,
    1,
    1,
    0
   ],
   [
    0,
    1,
    0,
    0,
    1,
    1
   ],
   [
    0,
    1,
    0,
    1,
    1,
    1
   ],
   [
    0,
    1,
    1,
    0,
    0,
    0
   ],
   [
    0,
    1,
    1,
    1,
    0,
    0
   ],
   [
    0,
    1,
    1,
    0,
    0,
    1
   ],
   [
    0,
    1,
    1,
    1,
    0,
    1
   ],
   [
    0,
    1,
    1,
    0,
    1,
    0
   ],
   [
    0,
    1,
    1,
    1,
    1,
    0
   ],
   [
    0,
    1,
    1,
    0,
    1,
    1
   ],
   [
    0,
    1,
    1,
    1,
    1,
    1
   ],
   [
    1,
    0,
    0,
    0,
    0,
    0
   ],
   [
    1,
    0,
    0,
    1,
    0,
    0
   ],
   [
    1,
    0,
    0,
    0,
    0,
    1
   ],
   [
    1,
    0,
    0,
    1,
    0,
    1
   ],
   [
    1,
    0,
    0,
    0,
    1,
    0
   ],
   [
    1,
    0,
    0,
    1,
    1,
    0
   ],
   [
    1,
    0,
    0,
    0,
    1,
    1
   ],
   [
    1,
    0,
    0,
    1,
    1,
    1
   ],
   [
    1,
    0,
    1,
    0,
    0,
    0
   ],
   [
    1,
    0,
    1,
    1,
    0,
    0
   ],
   [
    1,
    0,
    1,
    0,
    0,
    1
   ],
   [
    1,
    0,
    1,
    1,
    0,
    1
   ],
   [
    1,
    0,
    1,
    0,
    1,
    0
   ],
   [
    1,
    0,
    1,
    1,
    1,
    0
   ],
   [
    1,
    0,
    1,
    0,
    1,
    1
   ],
   [
    1,
    0,
    1,
    1,
    1,
    1
   ],
   [
    1,
    1,
    0,
    0,
    0,
    0
   ],
   [
    1,
    1,
    0,
    1,
    0,
    0
   ],
   [
    1,
    1,
    0,
    0,
    0,
    1
   ],
   [
    1,
    1,
    0,
    1,
    0,
    1
   ],
   [
    1,
    1,
    0,
    0,
    1,
    0
   ],
   [
    1,
    1,
    0,
    1,
    1,
    0
   ],
   [
    1,
    1,
    0,
    0,
    1,
    1
   ],
   [
    1,
    1,
    0,
    1,
    1,
    1
   ],
   [
    1,
    1,
    1,
    0,
    0,
    0
   ],
   [
    1,
    1,
    1,
    1,
    0,
    0
   ],
   [
    1,
    1,
    1,
    0,
    0,
    1
   ],
   [
    1,
    1,
    1,
    1,
    0,
    1
   ],
   [
    1,
    1,
    1,
    0,
    1,
    0
   ],
   [
    1,
    1,
    1,
    1,
    1,
    0
   ],
   [
    1,
    1,
    1,
    0,
    1,
    1
   ],
   [
    1,
    1,
    1,
    1,
    1,
    1
   ],
   [
    2,
    0,
    0,
    0,
    0,
    0
   ],
   [
    2,
    0,
    0,
    1,
    0,
    0
   ],
   [
    2,
    0,
    0,
    0,
    0,
    1
   ],
   [
    2,
    0,
    0,
    1,
    0,
    1
   ],
   [
    2,
    0,
    0,
    0,
    1,
    0
   ],
   [
    2,
    0,
    0,
    1,
    1,
    0
   ],
   [
    2,
    0,
    0,
    0,
    1,
    1
   ],
   [
    2,
    0,
    0,
    1,
    1,
    1
   ],
   [
    2,
    0,
    1,
    0,
    0,
    0
   ],
   [
    2,
    0,
    1,
    1,
    0,
    0
   ],
   [
    2,
    0,
    1,
    0,
    0,
    1
   ],
   [
    2,
    0,
    1,
    1,
    0,
    1
   ],
   [
    2,
    0,
    1,
    0,
    1,
    0
   ],
   [
    2,
    0,
    1,
    1,
    1,
    0
   ],
   [
    2,
    0,
    1,
    0,
    1,
    1
   ],
   [
    2,
    0,
    1,
    1,
    1,
    1
   ],
   [
    2,
    1,
    0,
    0,
    0,
    0
   ],
   [
    2,
    1,
    0,
    1,
    0,
    0
   ],
   [
    2,
    1,
    0,
    0,
    0,
    1
   ],
   [
    2,
    1,
    0,
    1,
    0,
    1
   ],
   [
    2,
    1,
    0,
    0,
    1,
    0
   ],
   [
    2,
    1,
    0,
    1,
    1,
    0
   ],
   [
    2,
    1,
    0,
    0,
    1,
    1
   ],
   [
    2,
    1,
    0,
    1,
    1,
    1
   ],
   [
    2,
    1,
    1,
    0,
    0,
    0
   ],
   [
    2,
    1,
    1,
    1,
    0,
    0
   ],
   [
    2,
    1,
    1,
    0,
    0,
    1
   ],
   [
    2,
    1,
    1,
    1,
    0,
    1
   ],
   [
    2,
    1,
    1,
    0,
    1,
    0
   ],
   [
    2,
    1,
    1,
    1,
    1,
    0
   ],
   [
    2,
    1,
    1,
    0,
    1,
    1
   ],
   [
    2,
    1,
    1,
    1,
    1,
    1
   ]
  ],
  "rows": [
   {
    "label": "util_escorting_tour",
    "expr": "escort",
    "c": [
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     2.491
    ]
   },
   {
    "label": "util_discretionary_tour",
    "expr": "othdiscr",
    "c": [
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0.903
    ]
   },
   {
    "label": "util_shopping_tour",
    "expr": "shopping",
    "c": [
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0
    ]
   },
   {
    "label": "util_maintenance_tour",
    "expr": "othmaint",
    "c": [
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     1.022
    ]
   },
   {
    "label": "util_visiting_or_social_tour",
    "expr": "social",
    "c": [
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0.769
    ]
   },
   {
    "label": "util_eating_out_tour",
    "expr": "eatout",
    "c": [
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0
    ]
   },
   {
    "label": "util_total_number_of_tours_is_0_no_prior_tours",
    "expr": "(tot_tours == 0) & (num_mand == 0) & (num_hh_joint_tours == 0)",
    "c": [
     -999,
     -999,
     -999,
     -999,
     -999,
     -999,
     -999,
     -999
    ]
   },
   {
    "label": "util_total_number_of_tours_is_0_prior_tours",
    "expr": "(tot_tours == 0) & ((num_mand > 0) | (num_hh_joint_tours > 0))",
    "c": [
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0
    ]
   },
   {
    "label": "util_total_number_of_tours_is_1",
    "expr": "tot_tours == 1",
    "c": [
     -7.3572,
     -7.6391,
     -6.2138,
     -8.9791,
     -8.5684,
     -7.1506,
     -7.4863,
     -5.759
    ]
   },
   {
    "label": "util_total_number_of_tours_is_2",
    "expr": "tot_tours == 2",
    "c": [
     -10.647,
     -10.4557,
     -8.908,
     -12.0248,
     -12.7416,
     -11.1214,
     -10.718,
     -11.517
    ]
   },
   {
    "label": "util_total_number_of_tours_is_3",
    "expr": "tot_tours == 3",
    "c": [
     -13.5005,
     -14.0176,
     -12.3261,
     -14.8516,
     -15.0978,
     -13.175,
     -13.7884,
     -17.276
    ]
   },
   {
    "label": "util_total_number_of_tours_is_4",
    "expr": "tot_tours == 4",
    "c": [
     -16.3965,
     -16.9717,
     -15.8114,
     -17.7037,
     -19.5439,
     -999,
     -999,
     -23.035
    ]
   },
   {
    "label": "util_total_number_of_tours_is_5",
    "expr": "tot_tours == 5",
    "c": [
     -19.6843,
     -999,
     -999,
     -999,
     -20.7897,
     -999,
     -999,
     -999
    ]
   },
   {
    "label": "util_total_number_of_tours_is_6_plus",
    "expr": "tot_tours > 5",
    "c": [
     -999,
     -999,
     -999,
     -999,
     -999,
     -999,
     -999,
     -999
    ]
   },
   {
    "label": "util_number_of_mandatory_tours_and_tour_frequency_is_0",
    "expr": "num_mand*(tot_tours == 0)",
    "c": [
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0
    ]
   },
   {
    "label": "util_number_of_mandatory_tours_and_tour_frequency_is_1",
    "expr": "num_mand*(tot_tours == 1)",
    "c": [
     0,
     -0.239,
     -0.1852,
     -0.6766,
     0,
     -0.234,
     -1.0331,
     0
    ]
   },
   {
    "label": "util_number_of_mandatory_tours_and_tour_frequency_is_2",
    "expr": "num_mand*(tot_tours == 2)",
    "c": [
     -0.8887,
     -1.8208,
     -0.8753,
     -1.0518,
     -5.0196,
     -0.9231,
     -2.7445,
     0
    ]
   },
   {
    "label": "util_number_of_mandatory_tours_and_tour_frequency_is_3",
    "expr": "num_mand*(tot_tours == 3)",
    "c": [
     -2.3343,
     -2.5923,
     -1.6158,
     -1.0518,
     -5.0196,
     -6.5835,
     -2.7445,
     0
    ]
   },
   {
    "label": "util_number_of_mandatory_tours_and_tour_frequency_is_4",
    "expr": "num_mand*(tot_tours == 4)",
    "c": [
     -2.3343,
     -2.5923,
     -999,
     -999,
     -999,
     -999,
     -999,
     0
    ]
   },
   {
    "label": "util_number_of_mandatory_tours_and_tour_frequency_is_5_plus",
    "expr": "num_mand*(tot_tours > 4)",
    "c": [
     -2.3343,
     -2.5923,
     -999,
     -999,
     -999,
     -999,
     -999,
     0
    ]
   },
   {
    "label": "util_number_of_joint_tours_and_tour_frequency_is_0",
    "expr": "num_hh_joint_tours*(tot_tours == 0)",
    "c": [
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0
    ]
   },
   {
    "label": "util_number_of_joint_tours_and_tour_frequency_is_1",
    "expr": "num_hh_joint_tours*(tot_tours == 1)",
    "c": [
     0,
     0,
     0,
     -0.1699,
     0,
     -0.2162,
     -0.6149,
     0
    ]
   },
   {
    "label": "util_number_of_joint_tours_and_tour_frequency_is_2",
    "expr": "num_hh_joint_tours*(tot_tours == 2)",
    "c": [
     0,
     -1.1986,
     -0.3153,
     -0.4285,
     -0.95,
     -0.3587,
     -0.6149,
     0
    ]
   },
   {
    "label": "util_number_of_joint_tours_and_tour_frequency_is_3",
    "expr": "num_hh_joint_tours*(tot_tours == 3)",
    "c": [
     0,
     -1.1986,
     -0.7351,
     -0.6551,
     -7.143,
     -4.2701,
     -999,
     0
    ]
   },
   {
    "label": "util_number_of_joint_tours_and_tour_frequency_is_4",
    "expr": "num_hh_joint_tours*(tot_tours == 4)",
    "c": [
     0,
     -1.1986,
     -999,
     -1.0411,
     -999,
     -999,
     -999,
     0
    ]
   },
   {
    "label": "util_number_of_joint_tours_and_tour_frequency_is_5_plus",
    "expr": "num_hh_joint_tours*(tot_tours >  4)",
    "c": [
     0,
     -999,
     -999,
     -1.0411,
     -999,
     -999,
     -999,
     0
    ]
   },
   {
    "label": "util_number_of_joint_shopping_tours",
    "expr": "shopping * num_hh_joint_shop_tours",
    "c": [
     0,
     0,
     -0.713,
     -0.2391,
     -0.8072,
     0,
     0,
     0
    ]
   },
   {
    "label": "util_number_of_joint_maintenance_tours",
    "expr": "othmaint * num_hh_joint_maint_tours",
    "c": [
     0,
     0,
     0,
     0,
     0,
     0,
     -1.3476,
     0
    ]
   },
   {
    "label": "util_number_of_joint_eating_out_tours",
    "expr": "eatout * num_hh_joint_eatout_tours",
    "c": [
     -0.5866,
     0,
     0,
     -0.7727,
     0,
     0,
     0,
     0
    ]
   },
   {
    "label": "util_number_of_joint_visit_tours",
    "expr": "social * num_hh_joint_social_tours",
    "c": [
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0
    ]
   },
   {
    "label": "util_number_of_joint_discretionary_tours",
    "expr": "othdiscr * num_hh_joint_othdiscr_tours",
    "c": [
     0,
     0,
     0.6713,
     0,
     0,
     0,
     0,
     0
    ]
   },
   {
    "label": "util_logged_maximum_residual_window_tour_frequency_is_0",
    "expr": "((num_mand > 0) | (num_hh_joint_tours > 0)) * log_max_window*(tot_tours == 0)",
    "c": [
     0,
     0,
     1.1858,
     0,
     0,
     0,
     0,
     0
    ]
   },
   {
    "label": "util_logged_maximum_residual_window_tour_frequency_is_1",
    "expr": "((num_mand > 0) | (num_hh_joint_tours > 0)) * log_max_window*(tot_tours == 1)",
    "c": [
     1.2562,
     1.5748,
     1.4842,
     1.7637,
     1.8357,
     1.3298,
     1.5603,
     0
    ]
   },
   {
    "label": "util_logged_maximum_residual_window_tour_frequency_is_2",
    "expr": "((num_mand > 0) | (num_hh_joint_tours > 0)) * log_max_window*(tot_tours == 2)",
    "c": [
     1.2868,
     2.0026,
     1.4842,
     1.7928,
     2.2707,
     1.3759,
     1.5603,
     0
    ]
   },
   {
    "label": "util_logged_maximum_residual_window_tour_frequency_is_3",
    "expr": "((num_mand > 0) | (num_hh_joint_tours > 0)) * log_max_window*(tot_tours == 3)",
    "c": [
     1.3993,
     2.0026,
     1.4842,
     1.7928,
     4.4023,
     3.2808,
     1.5603,
     0
    ]
   },
   {
    "label": "util_logged_maximum_residual_window_tour_frequency_is_4",
    "expr": "((num_mand > 0) | (num_hh_joint_tours > 0)) * log_max_window*(tot_tours == 4)",
    "c": [
     1.3993,
     2.0026,
     1.4842,
     1.7928,
     4.4023,
     3.2808,
     1.5603,
     0
    ]
   },
   {
    "label": "util_logged_maximum_residual_window_tour_frequency_is_5_plus",
    "expr": "((num_mand > 0) | (num_hh_joint_tours > 0)) * log_max_window*(tot_tours >  4)",
    "c": [
     1.3993,
     2.0026,
     1.4842,
     1.7928,
     4.4023,
     3.2808,
     1.5603,
     0
    ]
   },
   {
    "label": "util_mediumlow_income_group_and_tour_frequency_is_1",
    "expr": "medium_low_income & (tot_tours == 1)",
    "c": [
     0.4981,
     0.5981,
     0,
     0.5709,
     0,
     0,
     1.0873,
     0
    ]
   },
   {
    "label": "util_mediumlow_income_group_and_tour_frequency_is_2",
    "expr": "medium_low_income & (tot_tours == 2)",
    "c": [
     0.8345,
     0.9178,
     0,
     0.8315,
     0,
     0,
     1.0873,
     0
    ]
   },
   {
    "label": "util_mediumlow_income_group_and_tour_frequency_is_3",
    "expr": "medium_low_income & (tot_tours == 3)",
    "c": [
     1.0213,
     1.7539,
     0,
     0.8315,
     0,
     0,
     1.0873,
     0
    ]
   },
   {
    "label": "util_mediumlow_income_group_and_tour_frequency_is_4",
    "expr": "medium_low_income & (tot_tours == 4)",
    "c": [
     1.0213,
     1.7539,
     0,
     0.8315,
     0,
     0,
     1.0873,
     0
    ]
   },
   {
    "label": "util_mediumlow_income_group_and_tour_frequency_is_5_plus",
    "expr": "medium_low_income & (tot_tours >  4)",
    "c": [
     1.0213,
     1.7539,
     0,
     0.8315,
     0,
     0,
     1.0873,
     0
    ]
   },
   {
    "label": "util_mediumhigh_income_group_and_tour_frequency_is_1",
    "expr": "medium_high_income & (tot_tours == 1)",
    "c": [
     0.4981,
     0.8682,
     0.1109,
     0.7426,
     0,
     0,
     1.5197,
     0
    ]
   },
   {
    "label": "util_mediumhigh_income_group_and_tour_frequency_is_2",
    "expr": "medium_high_income & (tot_tours == 2)",
    "c": [
     0.8345,
     1.5362,
     0.3914,
     0.8546,
     0,
     0,
     1.5197,
     0
    ]
   },
   {
    "label": "util_mediumhigh_income_group_and_tour_frequency_is_3",
    "expr": "medium_high_income & (tot_tours == 3)",
    "c": [
     1.0213,
     1.9331,
     0.6137,
     1.0792,
     0,
     0,
     1.5197,
     0
    ]
   },
   {
    "label": "util_mediumhigh_income_group_and_tour_frequency_is_4",
    "expr": "medium_high_income & (tot_tours == 4)",
    "c": [
     1.0213,
     1.9331,
     0.6137,
     1.0792,
     0,
     0,
     1.5197,
     0
    ]
   },
   {
    "label": "util_mediumhigh_income_group_and_tour_frequency_is_5_plus",
    "expr": "medium_high_income & (tot_tours >  4)",
    "c": [
     1.0213,
     1.9331,
     0.6137,
     1.0792,
     0,
     0,
     1.5197,
     0
    ]
   },
   {
    "label": "util_high_income_group_and_tour_frequency_is_1",
    "expr": "high_income & (tot_tours == 1)",
    "c": [
     0.5189,
     0.8682,
     0.3986,
     1.0633,
     0,
     0,
     2.0175,
     0
    ]
   },
   {
    "label": "util_high_income_group_and_tour_frequency_is_2",
    "expr": "high_income & (tot_tours == 2)",
    "c": [
     1.1336,
     1.5362,
     0.8009,
     1.0633,
     0,
     0,
     2.0175,
     0
    ]
   },
   {
    "label": "util_high_income_group_and_tour_frequency_is_3",
    "expr": "high_income & (tot_tours == 3)",
    "c": [
     1.3899,
     1.9331,
     0.8254,
     1.7742,
     0,
     0,
     2.0175,
     0
    ]
   },
   {
    "label": "util_high_income_group_and_tour_frequency_is_4",
    "expr": "high_income & (tot_tours == 4)",
    "c": [
     1.3899,
     1.9331,
     0.8254,
     2.3941,
     0,
     0,
     2.0175,
     0
    ]
   },
   {
    "label": "util_high_income_group_and_tour_frequency_is_5_plus",
    "expr": "high_income & (tot_tours >  4)",
    "c": [
     1.3899,
     1.9331,
     0.8254,
     2.3941,
     0,
     0,
     2.0175,
     0
    ]
   },
   {
    "label": "util_mediumlow_income_group_and_shopping_tour",
    "expr": "medium_low_income * shopping",
    "c": [
     0,
     0.4421,
     0.5693,
     0.7734,
     1.0949,
     0,
     -0.6506,
     0
    ]
   },
   {
    "label": "util_mediumhigh_income_group_and_shopping_tour",
    "expr": "medium_high_income * shopping",
    "c": [
     0,
     0.4421,
     0.5693,
     0.8906,
     1.0949,
     0.2443,
     -0.6506,
     0
    ]
   },
   {
    "label": "util_high_income_group_and_shopping_tour",
    "expr": "high_income * shopping",
    "c": [
     0,
     0.7066,
     0.5693,
     0.9776,
     1.0949,
     0.2443,
     -0.6506,
     0
    ]
   },
   {
    "label": "util_mediumlow_income_group_and_maintenance_tour",
    "expr": "medium_low_income * othmaint",
    "c": [
     0,
     0.6763,
     0,
     0,
     0.7648,
     0,
     0,
     0
    ]
   },
   {
    "label": "util_mediumhigh_income_group_and_maintenance_tour",
    "expr": "medium_high_income * othmaint",
    "c": [
     0,
     0.6763,
     0,
     0,
     0.7648,
     0.3982,
     0,
     0
    ]
   },
   {
    "label": "util_high_income_group_and_maintenance_tour",
    "expr": "high_income * othmaint",
    "c": [
     0,
     0.6763,
     0,
     0,
     1.3795,
     0.3982,
     0,
     0
    ]
   },
   {
    "label": "util_mediumlow_income_group_and_eating_out_tour",
    "expr": "medium_low_income * eatout",
    "c": [
     0,
     0,
     0,
     0.2766,
     0.9769,
     0,
     -0.701,
     0
    ]
   },
   {
    "label": "util_mediumhigh_income_group_and_eating_out_tour",
    "expr": "medium_high_income * eatout",
    "c": [
     0.5581,
     0,
     -0.7207,
     0.4631,
     1.181,
     0.4916,
     -0.701,
     0
    ]
   },
   {
    "label": "util_high_income_group_and_eating_out_tour",
    "expr": "high_income * eatout",
    "c": [
     0.5581,
     0,
     -0.7207,
     0.7086,
     1.4842,
     0.4916,
     -0.701,
     0
    ]
   },
   {
    "label": "util_mediumlow_income_group_and_discretionary_tour",
    "expr": "medium_low_income * othdiscr",
    "c": [
     0,
     0.296,
     0,
     0.1707,
     1.0095,
     0.9169,
     0,
     0
    ]
   },
   {
    "label": "util_mediumhigh_income_group_and_discretionary_tour",
    "expr": "medium_high_income * othdiscr",
    "c": [
     0.2565,
     0.296,
     0,
     0.5009,
     1.0095,
     1.405,
     0,
     0
    ]
   },
   {
    "label": "util_high_income_group_and_discretionary_tour",
    "expr": "high_income * othdiscr",
    "c": [
     0.2565,
     0.296,
     0,
     0.8846,
     1.0095,
     2.327,
     0,
     0
    ]
   },
   {
    "label": "util_mediumlow_income_group_and_visiting_tour",
    "expr": "medium_low_income * social",
    "c": [
     0,
     -0.6868,
     0,
     -0.267,
     0,
     0,
     0,
     0
    ]
   },
   {
    "label": "util_mediumhigh_income_group_and_visiting_tour",
    "expr": "medium_high_income * social",
    "c": [
     -0.2423,
     -0.6868,
     -0.3694,
     -0.267,
     -0.4368,
     0.2858,
     0,
     0
    ]
   },
   {
    "label": "util_high_income_group_and_visiting_tour",
    "expr": "high_income * social",
    "c": [
     -0.2423,
     -0.6868,
     -0.3694,
     -0.9449,
     -0.5137,
     0.2858,
     0,
     0
    ]
   },
   {
    "label": "util_female_and_tour_frequency_is_1",
    "expr": "female & (tot_tours == 1)",
    "c": [
     -0.0766,
     0,
     0.0973,
     0.3902,
     -0.9348,
     0,
     0,
     0
    ]
   },
   {
    "label": "util_female_and_tour_frequency_is_2",
    "expr": "female & (tot_tours == 2)",
    "c": [
     -0.1062,
     0,
     0.2361,
     0.5323,
     -1.3028,
     0,
     0,
     0
    ]
   },
   {
    "label": "util_female_and_tour_frequency_is_3",
    "expr": "female & (tot_tours == 3)",
    "c": [
     -0.3274,
     0,
     1.9002,
     0.7452,
     -2.266,
     0,
     0,
     0
    ]
   },
   {
    "label": "util_female_and_tour_frequency_is_4",
    "expr": "female & (tot_tours == 4)",
    "c": [
     -0.3274,
     0,
     1.9002,
     1.1294,
     -2.266,
     0,
     0,
     0
    ]
   },
   {
    "label": "util_female_and_tour_frequency_is_5",
    "expr": "female & (tot_tours == 5)",
    "c": [
     -0.3274,
     0,
     1.9002,
     1.1294,
     -2.266,
     0,
     0,
     0
    ]
   },
   {
    "label": "util_female_and_escorting_tour",
    "expr": "female * escort",
    "c": [
     0.1824,
     0,
     0,
     0,
     0,
     0,
     0,
     0
    ]
   },
   {
    "label": "util_female_and_shopping_tour",
    "expr": "female * shopping",
    "c": [
     0,
     0.4524,
     0,
     0,
     0.9688,
     0,
     0,
     0
    ]
   },
   {
    "label": "util_female_and_maintenance_tour",
    "expr": "female * othmaint",
    "c": [
     0,
     0,
     0,
     -0.2464,
     0.7424,
     0,
     0,
     0
    ]
   },
   {
    "label": "util_female_and_eatingout_tour",
    "expr": "female * eatout",
    "c": [
     0,
     0,
     -0.6568,
     0,
     0,
     0,
     0,
     0
    ]
   },
   {
    "label": "util_female_and_discretionary_tour",
    "expr": "female * othdiscr",
    "c": [
     0,
     0.3072,
     -0.3266,
     0,
     0.4954,
     0,
     0,
     0
    ]
   },
   {
    "label": "util_zero_car_ownership_and_tour_frequency_is_1",
    "expr": "no_cars & (tot_tours == 1)",
    "c": [
     -0.3486,
     -0.5498,
     -0.581,
     -0.3623,
     0,
     -0.6369,
     0,
     0
    ]
   },
   {
    "label": "util_zero_car_ownership_and_tour_frequency_is_2",
    "expr": "no_cars & (tot_tours == 2)",
    "c": [
     -0.3486,
     -0.5498,
     -0.581,
     -1.272,
     0,
     -0.6369,
     0,
     0
    ]
   },
   {
    "label": "util_zero_car_ownership_and_tour_frequency_is_3",
    "expr": "no_cars & (tot_tours == 3)",
    "c": [
     -0.3486,
     -0.5498,
     -0.581,
     -1.9307,
     0,
     -0.6369,
     0,
     0
    ]
   },
   {
    "label": "util_zero_car_ownership_and_tour_frequency_is_4",
    "expr": "no_cars & (tot_tours == 4)",
    "c": [
     -0.3486,
     -0.5498,
     -0.581,
     -1.9307,
     0,
     -0.6369,
     0,
     0
    ]
   },
   {
    "label": "util_zero_car_ownership_and_tour_frequency_is_5_plus",
    "expr": "no_cars & (tot_tours >  4)",
    "c": [
     -0.3486,
     -0.5498,
     -0.581,
     -1.9307,
     0,
     -0.6369,
     0,
     0
    ]
   },
   {
    "label": "util_car_shortage_vs_workers_and_tour_frequency_is_1",
    "expr": "~no_cars & (car_sufficiency < 0) & (tot_tours == 1)",
    "c": [
     0,
     -0.5498,
     -0.581,
     -0.3623,
     0,
     -0.6369,
     0,
     0
    ]
   },
   {
    "label": "util_car_shortage_vs_workers_and_tour_frequency_is_2",
    "expr": "~no_cars & (car_sufficiency < 0) & (tot_tours == 2)",
    "c": [
     0,
     -0.5498,
     -0.581,
     -1.272,
     0,
     -0.6369,
     0,
     0
    ]
   },
   {
    "label": "util_car_shortage_vs_workers_and_tour_frequency_is_3",
    "expr": "~no_cars & (car_sufficiency < 0) & (tot_tours == 3)",
    "c": [
     0,
     -0.5498,
     -0.581,
     -1.9307,
     0,
     -0.6369,
     0,
     0
    ]
   },
   {
    "label": "util_car_shortage_vs_workers_and_tour_frequency_is_4",
    "expr": "~no_cars & (car_sufficiency < 0) & (tot_tours == 4)",
    "c": [
     0,
     -0.5498,
     -0.581,
     -1.9307,
     0,
     -0.6369,
     0,
     0
    ]
   },
   {
    "label": "util_car_shortage_vs_workers_and_tour_frequency_is_5_plus",
    "expr": "~no_cars & (car_sufficiency < 0) & (tot_tours > 4)",
    "c": [
     0,
     -0.5498,
     -0.581,
     -1.9307,
     0,
     -0.6369,
     0,
     0
    ]
   },
   {
    "label": "util_car_surplus_vs_workers_and_tour_frequency_is_1",
    "expr": "~no_cars & (car_sufficiency > 0) & (tot_tours == 1)",
    "c": [
     0.1304,
     0,
     0,
     0.7738,
     0.7965,
     0.2902,
     0,
     0
    ]
   },
   {
    "label": "util_car_surplus_vs_workers_and_tour_frequency_is_2",
    "expr": "~no_cars & (car_sufficiency > 0) & (tot_tours == 2)",
    "c": [
     0.1304,
     0,
     0,
     0.7738,
     2.1302,
     2.0352,
     0,
     0
    ]
   },
   {
    "label": "util_car_surplus_vs_workers_and_tour_frequency_is_3",
    "expr": "~no_cars & (car_sufficiency > 0) & (tot_tours == 3)",
    "c": [
     0.1304,
     0,
     0,
     0.7738,
     2.1302,
     2.0352,
     0,
     0
    ]
   },
   {
    "label": "util_car_surplus_vs_workers_and_tour_frequency_is_4",
    "expr": "~no_cars & (car_sufficiency > 0) & (tot_tours == 4)",
    "c": [
     0.1304,
     0,
     0,
     0.7738,
     2.1302,
     2.0352,
     0,
     0
    ]
   },
   {
    "label": "util_car_surplus_vs_workers_and_tour_frequency_is_5_plus",
    "expr": "~no_cars & (car_sufficiency > 0) & (tot_tours > 4)",
    "c": [
     0.1304,
     0,
     0,
     0.7738,
     2.1302,
     2.0352,
     0,
     0
    ]
   },
   {
    "label": "util_presence_of_non_worker_and_tour_frequency_is_1",
    "expr": "has_non_worker & (tot_tours == 1)",
    "c": [
     0,
     0,
     -0.8506,
     -0.3763,
     0.224,
     0,
     0.2177,
     0
    ]
   },
   {
    "label": "util_presence_of_non_worker_and_tour_frequency_is_2",
    "expr": "has_non_worker & (tot_tours == 2)",
    "c": [
     0,
     0,
     -1.1804,
     -0.719,
     0.2436,
     -0.6571,
     0.2177,
     0
    ]
   },
   {
    "label": "util_presence_of_non_worker_and_tour_frequency_is_3",
    "expr": "has_non_worker & (tot_tours == 3)",
    "c": [
     0,
     0,
     -1.1804,
     -1.0229,
     0.62,
     -1.4044,
     0.2177,
     0
    ]
   },
   {
    "label": "util_presence_of_non_worker_and_tour_frequency_is_4",
    "expr": "has_non_worker & (tot_tours == 4)",
    "c": [
     0,
     0,
     -1.1804,
     -1.0229,
     3.3742,
     -1.4044,
     0.2177,
     0
    ]
   },
   {
    "label": "util_presence_of_non_worker_and_tour_frequency_is_5",
    "expr": "has_non_worker & (tot_tours == 5)",
    "c": [
     0,
     0,
     -1.1804,
     -1.0229,
     3.3742,
     -1.4044,
     0.2177,
     0
    ]
   },
   {
    "label": "util_presence_of_retiree_and_tour_frequency_is_1",
    "expr": "has_retiree & (tot_tours == 1)",
    "c": [
     0,
     0,
     0,
     -0.464,
     -0.4458,
     0,
     0,
     0
    ]
   },
   {
    "label": "util_presence_of_retiree_and_tour_frequency_is_2",
    "expr": "has_retiree & (tot_tours == 2)",
    "c": [
     0,
     0,
     0,
     -0.4795,
     -0.5315,
     0,
     0,
     0
    ]
   },
   {
    "label": "util_presence_of_retiree_and_tour_frequency_is_3",
    "expr": "has_retiree & (tot_tours == 3)",
    "c": [
     0,
     0,
     0,
     -0.4795,
     -0.5315,
     0,
     0,
     0
    ]
   },
   {
    "label": "util_presence_of_retiree_and_tour_frequency_is_4",
    "expr": "has_retiree & (tot_tours == 4)",
    "c": [
     0,
     0,
     0,
     -0.4795,
     -0.5315,
     0,
     0,
     0
    ]
   },
   {
    "label": "util_presence_of_retiree_and_tour_frequency_is_5",
    "expr": "has_retiree & (tot_tours == 5)",
    "c": [
     0,
     0,
     0,
     -0.4795,
     -0.5315,
     0,
     0,
     0
    ]
   },
   {
    "label": "util_presence_of_preschool_kid_in_household_and_tour_frequency_is_1",
    "expr": "has_preschool_kid & (tot_tours == 1)",
    "c": [
     0,
     -0.1559,
     -0.9961,
     -0.7161,
     0,
     0,
     -0.4439,
     0
    ]
   },
   {
    "label": "util_presence_of_preschool_kid_in_household_and_tour_frequency_is_2",
    "expr": "has_preschool_kid & (tot_tours == 2)",
    "c": [
     0,
     -0.5681,
     -1.9096,
     -0.7161,
     0,
     0,
     -0.4439,
     0
    ]
   },
   {
    "label": "util_presence_of_preschool_kid_in_household_and_tour_frequency_is_3",
    "expr": "has_preschool_kid & (tot_tours == 3)",
    "c": [
     0,
     -0.5681,
     -2.8469,
     -0.7161,
     0,
     0,
     -0.4439,
     0
    ]
   },
   {
    "label": "util_presence_of_preschool_kid_in_household_and_tour_frequency_is_4",
    "expr": "has_preschool_kid & (tot_tours == 4)",
    "c": [
     0,
     -0.5681,
     -2.8469,
     -0.7161,
     0,
     0,
     -0.4439,
     0
    ]
   },
   {
    "label": "util_presence_of_preschool_kid_in_household_and_tour_frequency_is_5",
    "expr": "has_preschool_kid & (tot_tours == 5)",
    "c": [
     0,
     -0.5681,
     -2.8469,
     -0.7161,
     0,
     0,
     -0.4439,
     0
    ]
   },
   {
    "label": "util_presence_of_predriving_school_kid_in_household_and_tour_frequency_is_1",
    "expr": "has_school_kid & (tot_tours == 1)",
    "c": [
     0,
     0,
     0,
     0.1486,
     0,
     -0.3219,
     -0.2264,
     0
    ]
   },
   {
    "label": "util_presence_of_predriving_school_kid_in_household_and_tour_frequency_is_2",
    "expr": "has_school_kid & (tot_tours == 2)",
    "c": [
     0,
     0,
     0,
     0.484,
     0,
     -1.0874,
     -0.2264,
     0
    ]
   },
   {
    "label": "util_presence_of_predriving_school_kid_in_household_and_tour_frequency_is_3",
    "expr": "has_school_kid & (tot_tours == 3)",
    "c": [
     0,
     0,
     0,
     0.484,
     0,
     -1.0874,
     -0.2264,
     0
    ]
   },
   {
    "label": "util_presence_of_predriving_school_kid_in_household_and_tour_frequency_is_4",
    "expr": "has_school_kid & (tot_tours == 4)",
    "c": [
     0,
     0,
     0,
     0.484,
     0,
     -1.0874,
     -0.2264,
     0
    ]
   },
   {
    "label": "util_presence_of_predriving_school_kid_in_household_and_tour_frequency_is_5",
    "expr": "has_school_kid & (tot_tours == 5)",
    "c": [
     0,
     0,
     0,
     0.484,
     0,
     -1.0874,
     -0.2264,
     0
    ]
   },
   {
    "label": "util_presence_of_full_time_worker_and_escorting_tour",
    "expr": "has_full_time * escort",
    "c": [
     0,
     0,
     0,
     0.3947,
     0,
     0,
     0,
     -0.893
    ]
   },
   {
    "label": "util_presence_of_part_time_worker_and_escorting_tour",
    "expr": "has_part_time * escort",
    "c": [
     0,
     0,
     -1.8213,
     -0.5861,
     0,
     0,
     0,
     0
    ]
   },
   {
    "label": "util_presence_of_non_worker_and_escorting_tour",
    "expr": "has_non_worker * escort",
    "c": [
     -0.4815,
     -0.5263,
     0,
     0,
     0,
     0,
     0,
     0.89
    ]
   },
   {
    "label": "util_presence_of_retiree_and_escorting_tour",
    "expr": "has_retiree * escort",
    "c": [
     -0.808,
     -0.7516,
     0,
     0,
     0,
     0,
     0,
     0
    ]
   },
   {
    "label": "util_presence_of_university_student_and_escorting_tour",
    "expr": "has_university * escort",
    "c": [
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0
    ]
   },
   {
    "label": "util_presence_of_driving_school_kid_and_escorting_tour",
    "expr": "has_driving_kid * escort",
    "c": [
     0.3601,
     0.4164,
     0,
     0,
     0,
     0,
     0,
     0
    ]
   },
   {
    "label": "util_presence_of_pre_driving_school_kid_and_escorting_tour",
    "expr": "has_school_kid * escort",
    "c": [
     1.3974,
     1.5795,
     0.9489,
     1.3773,
     1.4903,
     0,
     0,
     0
    ]
   },
   {
    "label": "util_presence_of_pre_school_kid_and_escorting_tour",
    "expr": "has_preschool_kid * escort",
    "c": [
     0.6842,
     0.5414,
     2.1465,
     0.7194,
     0.5027,
     0,
     0,
     0
    ]
   },
   {
    "label": "util_at_home_pre_driving_school_kid_and_escorting_tour",
    "expr": "has_school_kid_at_home * escort",
    "c": [
     -0.2746,
     0,
     0,
     -1.148,
     0,
     0,
     0,
     0
    ]
   },
   {
    "label": "util_at_home_pre_school_kid_and_escorting_tour",
    "expr": "has_preschool_kid_at_home * escort",
    "c": [
     -1.5675,
     0,
     0,
     -0.1373,
     0,
     0,
     0,
     0
    ]
   },
   {
    "label": "util_presence_of_full_time_worker_and_shopping_tour",
    "expr": "has_full_time * shopping",
    "c": [
     -0.3059,
     0,
     -0.7728,
     0,
     -0.3609,
     0,
     0,
     0
    ]
   },
   {
    "label": "util_presence_of_part_time_worker_and_shopping_tour",
    "expr": "has_part_time * shopping",
    "c": [
     -0.1541,
     0,
     -0.5199,
     0,
     0,
     0,
     0,
     1.155
    ]
   },
   {
    "label": "util_presence_of_non_worker_and_shopping_tour",
    "expr": "has_non_worker * shopping",
    "c": [
     -0.416,
     0,
     0,
     0,
     0,
     0,
     -0.645,
     0.808
    ]
   },
   {
    "label": "util_presence_of_retiree_and_shopping_tour",
    "expr": "has_retiree * shopping",
    "c": [
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0
    ]
   },
   {
    "label": "util_presence_of_university_student_and_shopping_tour",
    "expr": "has_university * shopping",
    "c": [
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0
    ]
   },
   {
    "label": "util_presence_of_driving_school_kid_and_shopping_tour",
    "expr": "has_driving_kid * shopping",
    "c": [
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0
    ]
   },
   {
    "label": "util_presence_of_pre_driving_school_kid_and_shopping_tour",
    "expr": "has_school_kid * shopping",
    "c": [
     0,
     0,
     0,
     0,
     0,
     0,
     0.9365,
     0
    ]
   },
   {
    "label": "util_presence_of_pre_school_kid_and_shopping_tour",
    "expr": "has_preschool_kid * shopping",
    "c": [
     -0.208,
     0,
     1.3135,
     0,
     0,
     0,
     0,
     0
    ]
   },
   {
    "label": "util_at_home_pre_driving_school_kid_and_shopping_tour",
    "expr": "has_school_kid_at_home * shopping",
    "c": [
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0
    ]
   },
   {
    "label": "util_at_home_pre_school_kid_and_shopping_tour",
    "expr": "has_preschool_kid_at_home * shopping",
    "c": [
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0
    ]
   },
   {
    "label": "util_presence_of_full_time_worker_and_maintenance_tour",
    "expr": "has_full_time * othmaint",
    "c": [
     -0.1685,
     -0.3131,
     0,
     0,
     0,
     0,
     0,
     0
    ]
   },
   {
    "label": "util_presence_of_part_time_worker_and_maintenance_tour",
    "expr": "has_part_time * othmaint",
    "c": [
     -0.1584,
     -0.5621,
     0,
     0,
     0,
     0,
     0,
     0
    ]
   },
   {
    "label": "util_presence_of_non_worker_and_maintenance_tour",
    "expr": "has_non_worker * othmaint",
    "c": [
     -0.3237,
     0,
     0,
     0,
     0,
     0,
     0,
     0
    ]
   },
   {
    "label": "util_presence_of_retiree_and_maintenance_tour",
    "expr": "has_retiree * othmaint",
    "c": [
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0
    ]
   },
   {
    "label": "util_presence_of_university_student_and_maintenance_tour",
    "expr": "has_university * othmaint",
    "c": [
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0
    ]
   },
   {
    "label": "util_presence_of_driving_school_kid_and_maintenance_tour",
    "expr": "has_driving_kid * othmaint",
    "c": [
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0
    ]
   },
   {
    "label": "util_presence_of_pre_driving_school_kid_and_maintenance_tour",
    "expr": "has_school_kid * othmaint",
    "c": [
     0,
     0,
     0.3863,
     0,
     0,
     0,
     0,
     0
    ]
   },
   {
    "label": "util_presence_of_pre_school_kid_and_maintenance_tour",
    "expr": "has_preschool_kid * othmaint",
    "c": [
     0,
     0,
     0.9694,
     0,
     0,
     0,
     0,
     0
    ]
   },
   {
    "label": "util_at_home_pre_driving_school_kid_and_maintenance_tour",
    "expr": "has_school_kid_at_home * othmaint",
    "c": [
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0
    ]
   },
   {
    "label": "util_at_home_pre_school_kid_and_maintenance_tour",
    "expr": "has_preschool_kid_at_home * othmaint",
    "c": [
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0
    ]
   },
   {
    "label": "util_presence_of_full_time_worker_and_eating_out_tour",
    "expr": "has_full_time * eatout",
    "c": [
     -0.3571,
     0,
     -0.5251,
     -0.4667,
     -0.788,
     0,
     0,
     0
    ]
   },
   {
    "label": "util_presence_of_part_time_worker_and_eating_out_tour",
    "expr": "has_part_time * eatout",
    "c": [
     0,
     0,
     -1.9795,
     0,
     -0.788,
     0,
     0,
     1.037
    ]
   },
   {
    "label": "util_presence_of_non_worker_and_eating_out_tour",
    "expr": "has_non_worker * eatout",
    "c": [
     -0.2014,
     -0.6545,
     0,
     -0.4976,
     -0.788,
     0,
     -1.3074,
     1.157
    ]
   },
   {
    "label": "util_presence_of_retiree_and_eating_out_tour",
    "expr": "has_retiree * eatout",
    "c": [
     -0.5708,
     -1.389,
     0,
     -0.6911,
     -0.9282,
     0,
     0,
     0
    ]
   },
   {
    "label": "util_presence_of_university_student_and_eating_out_tour",
    "expr": "has_university * eatout",
    "c": [
     0,
     -1.4318,
     -0.6529,
     0,
     0,
     0,
     0,
     0
    ]
   },
   {
    "label": "util_presence_of_driving_school_kid_and_eating_out_tour",
    "expr": "has_driving_kid * eatout",
    "c": [
     0,
     0,
     0,
     0,
     0,
     -0.6377,
     0,
     0
    ]
   },
   {
    "label": "util_presence_of_pre_driving_school_kid_and_eating_out_tour",
    "expr": "has_school_kid * eatout",
    "c": [
     0,
     0,
     0,
     0,
     0,
     -1.5698,
     0,
     0
    ]
   },
   {
    "label": "util_presence_of_pre_school_kid_and_eating_out_tour",
    "expr": "has_preschool_kid * eatout",
    "c": [
     -0.4225,
     0,
     0,
     0,
     0,
     -0.2987,
     0,
     0
    ]
   },
   {
    "label": "util_at_home_pre_driving_school_kid_and_eating_out_tour",
    "expr": "has_school_kid_at_home * eatout",
    "c": [
     0,
     0,
     0,
     -0.3926,
     0,
     0,
     0,
     0
    ]
   },
   {
    "label": "util_at_home_pre_school_kid_and_eating_out_tour",
    "expr": "has_preschool_kid_at_home * eatout",
    "c": [
     0,
     0,
     0,
     -0.3926,
     0,
     0,
     0,
     0
    ]
   },
   {
    "label": "util_presence_of_full_time_worker_and_discretionary_tour",
    "expr": "has_full_time * othdiscr",
    "c": [
     -0.667,
     0,
     -0.4833,
     -0.3545,
     -0.4835,
     0,
     0.7526,
     0
    ]
   },
   {
    "label": "util_presence_of_part_time_worker_and_discretionary_tour",
    "expr": "has_part_time * othdiscr",
    "c": [
     -0.2102,
     0,
     0,
     -0.3545,
     0,
     0,
     0.3721,
     0
    ]
   },
   {
    "label": "util_presence_of_non_worker_and_discretionary_tour",
    "expr": "has_non_worker * othdiscr",
    "c": [
     -0.4281,
     -1.0371,
     0.9781,
     0,
     -0.5603,
     0,
     0,
     0.791
    ]
   },
   {
    "label": "util_presence_of_retiree_and_discretionary_tour",
    "expr": "has_retiree * othdiscr",
    "c": [
     -0.9104,
     0,
     0,
     0,
     0,
     0,
     0,
     0
    ]
   },
   {
    "label": "util_presence_of_university_student_and_discretionary_tour",
    "expr": "has_university * othdiscr",
    "c": [
     -0.8551,
     0,
     -0.6542,
     0,
     0,
     -1.2834,
     0,
     0
    ]
   },
   {
    "label": "util_presence_of_driving_school_kid_and_discretionary_tour",
    "expr": "has_driving_kid * othdiscr",
    "c": [
     -0.3963,
     0,
     0,
     0,
     0,
     -0.9202,
     0,
     0
    ]
   },
   {
    "label": "util_presence_of_pre_driving_school_kid_and_discretionary_tour",
    "expr": "has_school_kid * othdiscr",
    "c": [
     -0.3959,
     0,
     0,
     0,
     0,
     0,
     0,
     0
    ]
   },
   {
    "label": "util_presence_of_pre_school_kid_and_discretionary_tour",
    "expr": "has_preschool_kid * othdiscr",
    "c": [
     -0.5081,
     0,
     0,
     0,
     0,
     0,
     0,
     0
    ]
   },
   {
    "label": "util_at_home_pre_driving_school_kid_and_discretionary_tour",
    "expr": "has_school_kid_at_home * othdiscr",
    "c": [
     -0.4703,
     0,
     0,
     0,
     0,
     0,
     0,
     0
    ]
   },
   {
    "label": "util_at_home_pre_school_kid_and_discretionary_tour",
    "expr": "has_preschool_kid_at_home * othdiscr",
    "c": [
     -0.4703,
     0,
     0,
     0,
     0,
     0,
     0,
     0
    ]
   },
   {
    "label": "util_walk_access_to_retail_and_tour_frequency_is_1",
    "expr": "nmRetail * (tot_tours == 1)",
    "c": [
     0,
     0.0899,
     0,
     0.0713,
     0.0616,
     0,
     0,
     0
    ]
   },
   {
    "label": "util_walk_access_to_retail_and_tour_frequency_is_2",
    "expr": "nmRetail * (tot_tours == 2)",
    "c": [
     0,
     0.1447,
     0,
     0.1256,
     0.0616,
     0,
     0,
     0
    ]
   },
   {
    "label": "util_walk_access_to_retail_and_tour_frequency_is_3",
    "expr": "nmRetail * (tot_tours == 3)",
    "c": [
     0,
     0.3479,
     0,
     0.1508,
     0.0616,
     0,
     0,
     0
    ]
   },
   {
    "label": "util_walk_access_to_retail_and_tour_frequency_is_4",
    "expr": "nmRetail * (tot_tours == 4)",
    "c": [
     0,
     0.3479,
     0,
     0.1508,
     0.0616,
     0,
     0,
     0
    ]
   },
   {
    "label": "util_walk_access_to_retail_and_tour_frequency_is_5_plus",
    "expr": "nmRetail * (tot_tours > 4)",
    "c": [
     0,
     0.3479,
     0,
     0.1508,
     0.0616,
     0,
     0,
     0
    ]
   },
   {
    "label": "util_transit_access_to_retail_and_tour_frequency_is_1",
    "expr": "trOpRetail * (tot_tours == 1)",
    "c": [
     0.0226,
     0,
     0.0664,
     0,
     0,
     0,
     0,
     0
    ]
   },
   {
    "label": "util_transit_access_to_retail_and_tour_frequency_is_2",
    "expr": "trOpRetail * (tot_tours == 2)",
    "c": [
     0.0226,
     0,
     0.0664,
     0,
     0,
     0,
     0,
     0
    ]
   },
   {
    "label": "util_transit_access_to_retail_and_tour_frequency_is_3",
    "expr": "trOpRetail * (tot_tours == 3)",
    "c": [
     0.0226,
     0,
     0.0664,
     0,
     0,
     0,
     0,
     0
    ]
   },
   {
    "label": "util_transit_access_to_retail_and_tour_frequency_is_4",
    "expr": "trOpRetail * (tot_tours == 4)",
    "c": [
     0.0226,
     0,
     0.0664,
     0,
     0,
     0,
     0,
     0
    ]
   },
   {
    "label": "util_transit_access_to_retail_and_tour_frequency_is_5_plus",
    "expr": "trOpRetail * (tot_tours > 4)",
    "c": [
     0.0226,
     0,
     0.0664,
     0,
     0,
     0,
     0,
     0
    ]
   },
   {
    "label": "util_auto_access_to_retail_and_tour_frequency_is_1",
    "expr": "auOpRetail * (tot_tours == 1)",
    "c": [
     0,
     0,
     0,
     0,
     0,
     0.1004,
     0,
     0
    ]
   },
   {
    "label": "util_auto_access_to_retail_and_tour_frequency_is_2",
    "expr": "auOpRetail * (tot_tours == 2)",
    "c": [
     0,
     0,
     0,
     0,
     0,
     0.1004,
     0,
     0
    ]
   },
   {
    "label": "util_auto_access_to_retail_and_tour_frequency_is_3",
    "expr": "auOpRetail * (tot_tours == 3)",
    "c": [
     0,
     0,
     0,
     0,
     0,
     0.1004,
     0,
     0
    ]
   },
   {
    "label": "util_auto_access_to_retail_and_tour_frequency_is_4",
    "expr": "auOpRetail * (tot_tours == 4)",
    "c": [
     0,
     0,
     0,
     0,
     0,
     0.1004,
     0,
     0
    ]
   },
   {
    "label": "util_auto_access_to_retail_and_tour_frequency_is_5_plus",
    "expr": "auOpRetail * (tot_tours > 4)",
    "c": [
     0,
     0,
     0,
     0,
     0,
     0.1004,
     0,
     0
    ]
   },
   {
    "label": "util_walk_access_to_retail_and_escorting",
    "expr": "nmRetail * escort",
    "c": [
     0.0451,
     0,
     0,
     0,
     0,
     0,
     0,
     0
    ]
   },
   {
    "label": "util_transit_access_to_retail_and_escorting",
    "expr": "trOpRetail * escort",
    "c": [
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0
    ]
   },
   {
    "label": "util_auto_access_to_retail_and_escorting",
    "expr": "auOpRetail * escort",
    "c": [
     0,
     0,
     0,
     0,
     0,
     0,
     0.0629,
     0
    ]
   },
   {
    "label": "util_walk_access_to_retail_and_shopping",
    "expr": "nmRetail * shopping",
    "c": [
     0.033,
     0,
     0.0972,
     0.0598,
     0,
     0,
     0,
     0
    ]
   },
   {
    "label": "util_transit_access_to_retail_and_shopping",
    "expr": "trOpRetail * shopping",
    "c": [
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0
    ]
   },
   {
    "label": "util_auto_access_to_retail_and_shopping",
    "expr": "auOpRetail * shopping",
    "c": [
     0.1067,
     0,
     0,
     0,
     0,
     0,
     0,
     0
    ]
   },
   {
    "label": "util_walk_access_to_retail_and_maintenance",
    "expr": "nmRetail * othmaint",
    "c": [
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0
    ]
   },
   {
    "label": "util_transit_access_to_retail_and_maintenance",
    "expr": "trOpRetail * othmaint",
    "c": [
     0,
     0,
     0.0314,
     0,
     0,
     0,
     0,
     0
    ]
   },
   {
    "label": "util_auto_access_to_retail_and_maintenance",
    "expr": "auOpRetail * othmaint",
    "c": [
     0.0749,
     0,
     0,
     0.0956,
     0,
     0,
     0,
     0
    ]
   },
   {
    "label": "util_walk_access_to_retail_and_eating_out",
    "expr": "nmRetail * eatout",
    "c": [
     0.145,
     0,
     0,
     0,
     0,
     0,
     0.0738,
     0
    ]
   },
   {
    "label": "util_transit_access_to_retail_and_eating_out",
    "expr": "trOpRetail * eatout",
    "c": [
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0
    ]
   },
   {
    "label": "util_auto_access_to_retail_and_eating_out",
    "expr": "auOpRetail * eatout",
    "c": [
     0,
     0,
     0.1018,
     0,
     0,
     0,
     0,
     0
    ]
   },
   {
    "label": "util_walk_access_to_retail_and_discretionary",
    "expr": "nmRetail * othdiscr",
    "c": [
     0.0567,
     0,
     0,
     0.0772,
     0,
     0,
     0,
     0
    ]
   },
   {
    "label": "util_transit_access_to_retail_and_discretionary",
    "expr": "trOpRetail * othdiscr",
    "c": [
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0
    ]
   },
   {
    "label": "util_auto_access_to_retail_and_discretionary",
    "expr": "auOpRetail * othdiscr",
    "c": [
     0.0844,
     0,
     0.094,
     0,
     0,
     0,
     0,
     0
    ]
   },
   {
    "label": "util_urban_and_tour_frequency_is_1",
    "expr": "home_is_urban & (tot_tours == 1)",
    "c": [
     0,
     0,
     -1.1648,
     0,
     0,
     0,
     0,
     0
    ]
   },
   {
    "label": "util_urban_and_tour_frequency_is_2",
    "expr": "home_is_urban & (tot_tours == 2)",
    "c": [
     0,
     0,
     -2.3177,
     0,
     0,
     0,
     0,
     0
    ]
   },
   {
    "label": "util_urban_and_tour_frequency_is_3",
    "expr": "home_is_urban & (tot_tours == 3)",
    "c": [
     0,
     0,
     -2.5027,
     0,
     0,
     0,
     0,
     0
    ]
   },
   {
    "label": "util_urban_and_tour_frequency_is_4",
    "expr": "home_is_urban & (tot_tours == 4)",
    "c": [
     0,
     0,
     -2.5027,
     0,
     0,
     0,
     0,
     0
    ]
   },
   {
    "label": "util_urban_and_tour_frequency_is_5_plus",
    "expr": "home_is_urban & (tot_tours > 4)",
    "c": [
     0,
     0,
     -2.5027,
     0,
     0,
     0,
     0,
     0
    ]
   },
   {
    "label": "util_urban_and_escorting_tour",
    "expr": "home_is_urban * escort",
    "c": [
     -0.4316,
     -0.3929,
     0.8516,
     0,
     0,
     0,
     0.4352,
     0
    ]
   },
   {
    "label": "util_urban_and_shopping_tour",
    "expr": "home_is_urban * shopping",
    "c": [
     0,
     0,
     0.533,
     0,
     0,
     0,
     0,
     0
    ]
   },
   {
    "label": "util_urban_and_maintenance_tour",
    "expr": "home_is_urban * othmaint",
    "c": [
     0,
     0,
     1.0316,
     0,
     0,
     1.0394,
     0,
     0
    ]
   },
   {
    "label": "util_urban_and_eatingout_tour",
    "expr": "home_is_urban * eatout",
    "c": [
     0,
     0,
     0.68,
     0,
     0,
     0,
     0,
     0
    ]
   },
   {
    "label": "util_urban_and_discretionary_tour",
    "expr": "home_is_urban * othdiscr",
    "c": [
     0,
     0,
     0.9563,
     0,
     0,
     0,
     0,
     0
    ]
   },
   {
    "label": "util_1_escort_tour_constant",
    "expr": "escort == 1",
    "c": [
     0.0298,
     0.5272,
     1.7028,
     -0.0629,
     -0.3992,
     -0.4934,
     -0.7551,
     0.3622
    ]
   },
   {
    "label": "util_2_plus_escort_tours_constant",
    "expr": "escort >= 2",
    "c": [
     0.7402,
     1.5987,
     2.8379,
     0.9273,
     0.5175,
     1.4155,
     -0.0086,
     2.2219
    ]
   },
   {
    "label": "util_1_plus_shopping_tours_constant",
    "expr": "shopping >= 1",
    "c": [
     0.4774,
     0.7569,
     1.8403,
     0.4683,
     0.5947,
     0.532,
     0.4783,
     1.6919
    ]
   },
   {
    "label": "util_1_plus_maintenance_tours_constant",
    "expr": "othmaint >= 1",
    "c": [
     0.1202,
     0.5533,
     0.3348,
     -0.0653,
     0.1046,
     -0.4344,
     -0.506,
     0.6788
    ]
   },
   {
    "label": "util_1_plus_eating_out_tours_constant",
    "expr": "eatout >= 1",
    "c": [
     0.0097,
     0.6914,
     2.0723,
     -0.1429,
     0.0245,
     -0.0242,
     1.1145,
     0.9612
    ]
   },
   {
    "label": "util_1_plus_visting_tours_constant",
    "expr": "social >= 1",
    "c": [
     0.0522,
     0.1405,
     1.2172,
     -0.1272,
     0.2789,
     0.2367,
     -0.4006,
     0.4424
    ]
   },
   {
    "label": "util_1_plus_other_discretionary_tours_constant",
    "expr": "othdiscr >= 1",
    "c": [
     0.7412,
     0.7989,
     1.3389,
     0.3334,
     0.4282,
     -0.2602,
     0.4634,
     1.4935
    ]
   },
   {
    "label": "util_0_auto_household_and_escorting_tour",
    "expr": "escort * no_cars",
    "c": [
     -2,
     -2,
     -2,
     -2,
     -2,
     -2,
     -2,
     -2
    ]
   }
  ],
  "extension": [
   [
    1,
    0,
    0,
    1,
    0.829545455,
    1,
    1
   ],
   [
    2,
    0,
    0,
    1,
    0.769230769,
    1,
    1
   ],
   [
    3,
    0,
    0,
    1,
    0.893939394,
    1,
    1
   ],
   [
    4,
    0,
    0,
    1,
    0.75,
    1,
    1
   ],
   [
    5,
    0,
    0,
    1,
    0.842105263,
    1,
    1
   ],
   [
    6,
    0,
    0,
    1,
    0.714285714,
    1,
    1
   ],
   [
    7,
    0,
    0,
    1,
    0.814814815,
    1,
    1
   ],
   [
    8,
    0,
    0,
    1,
    0.75,
    1,
    1
   ],
   [
    1,
    1,
    0,
    1,
    0.789473684,
    1,
    1
   ],
   [
    2,
    1,
    0,
    1,
    0.6,
    1,
    1
   ],
   [
    3,
    1,
    0,
    1,
    1,
    1,
    1
   ],
   [
    4,
    1,
    0,
    1,
    1,
    1,
    1
   ],
   [
    5,
    1,
    0,
    1,
    0.825910931,
    1,
    1
   ],
   [
    6,
    1,
    0,
    1,
    0.837209302,
    1,
    1
   ],
   [
    7,
    1,
    0,
    1,
    0.6,
    1,
    1
   ],
   [
    8,
    1,
    0,
    1,
    1,
    1,
    1
   ],
   [
    1,
    0,
    1,
    1,
    0.842105263,
    1,
    1
   ],
   [
    2,
    0,
    1,
    1,
    1,
    1,
    1
   ],
   [
    3,
    0,
    1,
    1,
    1,
    1,
    1
   ],
   [
    4,
    0,
    1,
    1,
    1,
    1,
    1
   ],
   [
    5,
    0,
    1,
    1,
    1,
    1,
    1
   ],
   [
    6,
    0,
    1,
    1,
    1,
    1,
    1
   ],
   [
    7,
    0,
    1,
    1,
    1,
    1,
    1
   ],
   [
    8,
    0,
    1,
    1,
    1,
    1,
    1
   ],
   [
    1,
    1,
    1,
    1,
    1,
    1,
    1
   ],
   [
    2,
    1,
    1,
    1,
    1,
    1,
    1
   ],
   [
    3,
    1,
    1,
    1,
    1,
    1,
    1
   ],
   [
    4,
    1,
    1,
    1,
    1,
    1,
    1
   ],
   [
    5,
    1,
    1,
    1,
    0.777777778,
    1,
    1
   ],
   [
    6,
    1,
    1,
    1,
    1,
    1,
    1
   ],
   [
    7,
    1,
    1,
    1,
    1,
    1,
    1
   ],
   [
    8,
    1,
    1,
    1,
    1,
    1,
    1
   ],
   [
    1,
    0,
    0,
    2,
    0.892694064,
    0.99086758,
    1
   ],
   [
    2,
    0,
    0,
    2,
    0.84057971,
    0.992753623,
    1
   ],
   [
    3,
    0,
    0,
    2,
    0.971014493,
    1,
    1
   ],
   [
    4,
    0,
    0,
    2,
    0.96969697,
    1,
    1
   ],
   [
    5,
    0,
    0,
    2,
    0.870056497,
    0.994350282,
    1
   ],
   [
    6,
    0,
    0,
    2,
    0.866666667,
    1,
    1
   ],
   [
    7,
    0,
    0,
    2,
    0.971014493,
    1,
    1
   ],
   [
    8,
    0,
    0,
    2,
    0.931034483,
    1,
    1
   ],
   [
    1,
    1,
    0,
    2,
    0.885057471,
    1,
    1
   ],
   [
    2,
    1,
    0,
    2,
    0.727272727,
    1,
    1
   ],
   [
    3,
    1,
    0,
    2,
    0.971428571,
    1,
    1
   ],
   [
    4,
    1,
    0,
    2,
    1,
    1,
    1
   ],
   [
    5,
    1,
    0,
    2,
    0.895977809,
    0.993065187,
    1
   ],
   [
    6,
    1,
    0,
    2,
    0.885185185,
    1,
    1
   ],
   [
    7,
    1,
    0,
    2,
    1,
    1,
    1
   ],
   [
    8,
    1,
    0,
    2,
    1,
    1,
    1
   ],
   [
    1,
    0,
    1,
    2,
    0.910087719,
    0.993421053,
    1
   ],
   [
    2,
    0,
    1,
    2,
    0.88,
    1,
    1
   ],
   [
    3,
    0,
    1,
    2,
    0.8,
    1,
    1
   ],
   [
    4,
    0,
    1,
    2,
    1,
    1,
    1
   ],
   [
    5,
    0,
    1,
    2,
    1,
    1,
    1
   ],
   [
    6,
    0,
    1,
    2,
    1,
    1,
    1
   ],
   [
    7,
    0,
    1,
    2,
    1,
    1,
    1
   ],
   [
    8,
    0,
    1,
    2,
    1,
    1,
    1
   ],
   [
    1,
    1,
    1,
    2,
    1,
    1,
    1
   ],
   [
    2,
    1,
    1,
    2,
    1,
    1,
    1
   ],
   [
    3,
    1,
    1,
    2,
    1,
    1,
    1
   ],
   [
    4,
    1,
    1,
    2,
    1,
    1,
    1
   ],
   [
    5,
    1,
    1,
    2,
    1,
    1,
    1
   ],
   [
    6,
    1,
    1,
    2,
    0.964912281,
    1,
    1
   ],
   [
    7,
    1,
    1,
    2,
    1,
    1,
    1
   ],
   [
    8,
    1,
    1,
    2,
    0.888888889,
    1,
    1
   ],
   [
    1,
    0,
    0,
    3,
    0.935643564,
    0.997524752,
    1
   ],
   [
    2,
    0,
    0,
    3,
    0.905660377,
    1,
    1
   ],
   [
    3,
    0,
    0,
    3,
    0.978813559,
    1,
    1
   ],
   [
    4,
    0,
    0,
    3,
    0.928571429,
    1,
    1
   ],
   [
    5,
    0,
    0,
    3,
    0.901515152,
    0.992424242,
    1
   ],
   [
    6,
    0,
    0,
    3,
    0.863636364,
    1,
    1
   ],
   [
    7,
    0,
    0,
    3,
    0.947368421,
    1,
    1
   ],
   [
    8,
    0,
    0,
    3,
    0.913043478,
    1,
    1
   ],
   [
    1,
    1,
    0,
    3,
    0.893333333,
    0.986666667,
    1
   ],
   [
    2,
    1,
    0,
    3,
    1,
    1,
    1
   ],
   [
    3,
    1,
    0,
    3,
    1,
    1,
    1
   ],
   [
    4,
    1,
    0,
    3,
    0.857142857,
    1,
    1
   ],
   [
    5,
    1,
    0,
    3,
    0.916071429,
    0.996428571,
    1
   ],
   [
    6,
    1,
    0,
    3,
    0.856382979,
    0.984042553,
    1
   ],
   [
    7,
    1,
    0,
    3,
    1,
    1,
    1
   ],
   [
    8,
    1,
    0,
    3,
    1,
    1,
    1
   ],
   [
    1,
    0,
    1,
    3,
    0.916201117,
    0.991620112,
    1
   ],
   [
    2,
    0,
    1,
    3,
    0.912280702,
    0.98245614,
    1
   ],
   [
    3,
    0,
    1,
    3,
    1,
    1,
    1
   ],
   [
    4,
    0,
    1,
    3,
    1,
    1,
    1
   ],
   [
    5,
    0,
    1,
    3,
    1,
    1,
    1
   ],
   [
    6,
    0,
    1,
    3,
    0.833333333,
    1,
    1
   ],
   [
    7,
    0,
    1,
    3,
    0.961538462,
    1,
    1
   ],
   [
    8,
    0,
    1,
    3,
    1,
    1,
    1
   ],
   [
    1,
    1,
    1,
    3,
    0.97826087,
    0.989130435,
    1
   ],
   [
    2,
    1,
    1,
    3,
    0.97260274,
    1,
    1
   ],
   [
    3,
    1,
    1,
    3,
    1,
    1,
    1
   ],
   [
    4,
    1,
    1,
    3,
    1,
    1,
    1
   ],
   [
    5,
    1,
    1,
    3,
    0.995762712,
    1,
    1
   ],
   [
    6,
    1,
    1,
    3,
    0.921568627,
    0.980392157,
    1
   ],
   [
    7,
    1,
    1,
    3,
    1,
    1,
    1
   ],
   [
    8,
    1,
    1,
    3,
    1,
    1,
    1
   ],
   [
    1,
    0,
    0,
    4,
    0.9218107,
    0.995884774,
    1
   ],
   [
    2,
    0,
    0,
    4,
    0.900900901,
    1,
    1
   ],
   [
    3,
    0,
    0,
    4,
    0.997354497,
    1,
    1
   ],
   [
    4,
    0,
    0,
    4,
    0.991176471,
    1,
    1
   ],
   [
    5,
    0,
    0,
    4,
    0.921568627,
    0.980392157,
    1
   ],
   [
    6,
    0,
    0,
    4,
    0.954545455,
    1,
    1
   ],
   [
    7,
    0,
    0,
    4,
    1,
    1,
    1
   ],
   [
    8,
    0,
    0,
    4,
    0.954545455,
    1,
    1
   ],
   [
    1,
    1,
    0,
    4,
    0.941176471,
    0.970588235,
    1
   ],
   [
    2,
    1,
    0,
    4,
    0.925925926,
    1,
    1
   ],
   [
    3,
    1,
    0,
    4,
    1,
    1,
    1
   ],
   [
    4,
    1,
    0,
    4,
    0.875,
    1,
    1
   ],
   [
    5,
    1,
    0,
    4,
    0.915322581,
    1,
    1
   ],
   [
    6,
    1,
    0,
    4,
    0.947674419,
    0.994186047,
    1
   ],
   [
    7,
    1,
    0,
    4,
    0.666666667,
    1,
    1
   ],
   [
    8,
    1,
    0,
    4,
    1,
    1,
    1
   ],
   [
    1,
    0,
    1,
    4,
    0.925925926,
    0.987654321,
    1
   ],
   [
    2,
    0,
    1,
    4,
    0.903703704,
    1,
    1
   ],
   [
    3,
    0,
    1,
    4,
    1,
    1,
    1
   ],
   [
    4,
    0,
    1,
    4,
    1,
    1,
    1
   ],
   [
    5,
    0,
    1,
    4,
    1,
    1,
    1
   ],
   [
    6,
    0,
    1,
    4,
    1,
    1,
    1
   ],
   [
    7,
    0,
    1,
    4,
    1,
    1,
    1
   ],
   [
    8,
    0,
    1,
    4,
    1,
    1,
    1
   ],
   [
    1,
    1,
    1,
    4,
    1,
    1,
    1
   ],
   [
    2,
    1,
    1,
    4,
    0.911111111,
    1,
    1
   ],
   [
    3,
    1,
    1,
    4,
    1,
    1,
    1
   ],
   [
    4,
    1,
    1,
    4,
    1,
    1,
    1
   ],
   [
    5,
    1,
    1,
    4,
    1,
    1,
    1
   ],
   [
    6,
    1,
    1,
    4,
    0.962962963,
    1,
    1
   ],
   [
    7,
    1,
    1,
    4,
    1,
    1,
    1
   ],
   [
    8,
    1,
    1,
    4,
    1,
    1,
    1
   ],
   [
    1,
    0,
    0,
    5,
    0.976744186,
    1,
    1
   ],
   [
    2,
    0,
    0,
    5,
    0.981818182,
    1,
    1
   ],
   [
    3,
    0,
    0,
    5,
    0.985915493,
    1,
    1
   ],
   [
    4,
    0,
    0,
    5,
    1,
    1,
    1
   ],
   [
    5,
    0,
    0,
    5,
    1,
    1,
    1
   ],
   [
    6,
    0,
    0,
    5,
    1,
    1,
    1
   ],
   [
    7,
    0,
    0,
    5,
    1,
    1,
    1
   ],
   [
    8,
    0,
    0,
    5,
    0.875,
    1,
    1
   ],
   [
    1,
    1,
    0,
    5,
    1,
    1,
    1
   ],
   [
    2,
    1,
    0,
    5,
    1,
    1,
    1
   ],
   [
    3,
    1,
    0,
    5,
    0.964285714,
    1,
    1
   ],
   [
    4,
    1,
    0,
    5,
    1,
    1,
    1
   ],
   [
    5,
    1,
    0,
    5,
    0.985714286,
    1,
    1
   ],
   [
    6,
    1,
    0,
    5,
    0.951807229,
    1,
    1
   ],
   [
    7,
    1,
    0,
    5,
    1,
    1,
    1
   ],
   [
    8,
    1,
    0,
    5,
    1,
    1,
    1
   ],
   [
    1,
    0,
    1,
    5,
    0.926605505,
    1,
    1
   ],
   [
    2,
    0,
    1,
    5,
    0.941176471,
    1,
    1
   ],
   [
    3,
    0,
    1,
    5,
    1,
    1,
    1
   ],
   [
    4,
    0,
    1,
    5,
    1,
    1,
    1
   ],
   [
    5,
    0,
    1,
    5,
    1,
    1,
    1
   ],
   [
    6,
    0,
    1,
    5,
    1,
    1,
    1
   ],
   [
    7,
    0,
    1,
    5,
    1,
    1,
    1
   ],
   [
    8,
    0,
    1,
    5,
    1,
    1,
    1
   ],
   [
    1,
    1,
    1,
    5,
    1,
    1,
    1
   ],
   [
    2,
    1,
    1,
    5,
    1,
    1,
    1
   ],
   [
    3,
    1,
    1,
    5,
    0.972972973,
    1,
    1
   ],
   [
    4,
    1,
    1,
    5,
    1,
    1,
    1
   ],
   [
    5,
    1,
    1,
    5,
    1,
    1,
    1
   ],
   [
    6,
    1,
    1,
    5,
    0.933333333,
    1,
    1
   ],
   [
    7,
    1,
    1,
    5,
    1,
    1,
    1
   ],
   [
    8,
    1,
    1,
    5,
    1,
    1,
    1
   ],
   [
    1,
    0,
    0,
    6,
    0.93837535,
    0.988795518,
    1
   ],
   [
    2,
    0,
    0,
    6,
    0.888888889,
    1,
    1
   ],
   [
    3,
    0,
    0,
    6,
    0.966832504,
    0.998341625,
    1
   ],
   [
    4,
    0,
    0,
    6,
    0.942028986,
    1,
    1
   ],
   [
    5,
    0,
    0,
    6,
    0.88034188,
    1,
    1
   ],
   [
    6,
    0,
    0,
    6,
    0.925925926,
    1,
    1
   ],
   [
    7,
    0,
    0,
    6,
    0.967741935,
    1,
    1
   ],
   [
    8,
    0,
    0,
    6,
    0.90625,
    1,
    1
   ],
   [
    1,
    1,
    0,
    6,
    0.85915493,
    1,
    1
   ],
   [
    2,
    1,
    0,
    6,
    0.818181818,
    0.96969697,
    1
   ],
   [
    3,
    1,
    0,
    6,
    1,
    1,
    1
   ],
   [
    4,
    1,
    0,
    6,
    0.952380952,
    1,
    1
   ],
   [
    5,
    1,
    0,
    6,
    0.879237288,
    0.997881356,
    1
   ],
   [
    6,
    1,
    0,
    6,
    0.862944162,
    0.984771574,
    1
   ],
   [
    7,
    1,
    0,
    6,
    0.9,
    1,
    1
   ],
   [
    8,
    1,
    0,
    6,
    1,
    1,
    1
   ],
   [
    1,
    0,
    1,
    6,
    0.927835052,
    0.996563574,
    1
   ],
   [
    2,
    0,
    1,
    6,
    0.859375,
    0.9921875,
    1
   ],
   [
    3,
    0,
    1,
    6,
    1,
    1,
    1
   ],
   [
    4,
    0,
    1,
    6,
    1,
    1,
    1
   ],
   [
    5,
    0,
    1,
    6,
    0.92,
    1,
    1
   ],
   [
    6,
    0,
    1,
    6,
    1,
    1,
    1
   ],
   [
    7,
    0,
    1,
    6,
    0.904761905,
    1,
    1
   ],
   [
    8,
    0,
    1,
    6,
    1,
    1,
    1
   ],
   [
    1,
    1,
    1,
    6,
    0.982758621,
    1,
    1
   ],
   [
    2,
    1,
    1,
    6,
    0.927710843,
    0.987951807,
    1
   ],
   [
    3,
    1,
    1,
    6,
    0.982954545,
    1,
    1
   ],
   [
    4,
    1,
    1,
    6,
    0.938679245,
    1,
    1
   ],
   [
    5,
    1,
    1,
    6,
    1,
    1,
    1
   ],
   [
    6,
    1,
    1,
    6,
    0.9375,
    1,
    1
   ],
   [
    7,
    1,
    1,
    6,
    1,
    1,
    1
   ],
   [
    8,
    1,
    1,
    6,
    1,
    1,
    1
   ]
  ]
 },
 "workplace": {
  "dist": [
   -0.8428,
   -0.3104,
   -0.3783,
   -0.1285,
   -0.0917
  ],
  "dist05High": 0.15,
  "dist5upHigh": 0.02,
  "logsum": 0.3
 },
 "school": {
  "univ": [
   -3.2451,
   -2.7011,
   -0.5707,
   -0.5002,
   -0.073
  ],
  "high": [
   -0.9523,
   -0.57,
   -0.57,
   -0.193,
   -0.1882
  ],
  "grade": [
   -1.6419,
   -0.57,
   -0.57,
   -0.2031,
   -0.046
  ],
  "logsum": 0.5358
 },
 "sizeTerms": {
  "workplace:work_low": {
   "RETEMPN": 0.129,
   "FPSEMPN": 0.193,
   "HEREMPN": 0.383,
   "OTHEMPN": 0.12,
   "AGREMPN": 0.01,
   "MWTEMPN": 0.164
  },
  "workplace:work_med": {
   "RETEMPN": 0.12,
   "FPSEMPN": 0.197,
   "HEREMPN": 0.325,
   "OTHEMPN": 0.139,
   "AGREMPN": 0.008,
   "MWTEMPN": 0.21
  },
  "workplace:work_high": {
   "RETEMPN": 0.11,
   "FPSEMPN": 0.207,
   "HEREMPN": 0.284,
   "OTHEMPN": 0.154,
   "AGREMPN": 0.006,
   "MWTEMPN": 0.239
  },
  "workplace:work_veryhigh": {
   "RETEMPN": 0.093,
   "FPSEMPN": 0.27,
   "HEREMPN": 0.241,
   "OTHEMPN": 0.146,
   "AGREMPN": 0.004,
   "MWTEMPN": 0.246
  },
  "school:university": {
   "COLLFTE": 0.592,
   "COLLPTE": 0.408
  },
  "school:gradeschool": {
   "AGE0519": 1
  },
  "school:highschool": {
   "HSENROLL": 1
  },
  "non_mandatory:escort": {
   "RETEMPN": 0.225,
   "HEREMPN": 0.144,
   "AGE0519": 0.465,
   "HSENROLL": 0.166
  },
  "non_mandatory:shopping": {
   "RETEMPN": 1
  },
  "non_mandatory:eatout": {
   "RETEMPN": 0.742,
   "HEREMPN": 0.258
  },
  "non_mandatory:othmaint": {
   "RETEMPN": 0.482,
   "HEREMPN": 0.518
  },
  "non_mandatory:social": {
   "RETEMPN": 0.522,
   "HEREMPN": 0.478
  },
  "non_mandatory:othdiscr": {
   "TOTHH": 0.252,
   "RETEMPN": 0.212,
   "HEREMPN": 0.272,
   "OTHEMPN": 0.165,
   "HSENROLL": 0.098
  },
  "atwork:atwork": {
   "RETEMPN": 0.742,
   "HEREMPN": 0.258
  },
  "trip:work": {
   "RETEMPN": 1,
   "FPSEMPN": 1,
   "HEREMPN": 1,
   "OTHEMPN": 1,
   "AGREMPN": 1,
   "MWTEMPN": 1
  },
  "trip:escort": {
   "TOTHH": 0.001,
   "RETEMPN": 0.225,
   "HEREMPN": 0.144,
   "AGE0519": 0.464,
   "HSENROLL": 0.166
  },
  "trip:shopping": {
   "TOTHH": 0.001,
   "RETEMPN": 0.999
  },
  "trip:eatout": {
   "RETEMPN": 0.742,
   "HEREMPN": 0.258
  },
  "trip:othmaint": {
   "TOTHH": 0.001,
   "RETEMPN": 0.481,
   "HEREMPN": 0.518
  },
  "trip:social": {
   "TOTHH": 0.001,
   "RETEMPN": 0.521,
   "HEREMPN": 0.478
  },
  "trip:othdiscr": {
   "TOTHH": 0.252,
   "RETEMPN": 0.212,
   "HEREMPN": 0.272,
   "OTHEMPN": 0.165,
   "HSENROLL": 0.098
  },
  "trip:univ": {
   "TOTHH": 0.001,
   "COLLFTE": 0.592,
   "COLLPTE": 0.408
  }
 },
 "accessibility": {
  "autoDispersion": -0.05,
  "transitDispersion": -0.05,
  "walkDispersion": -1,
  "maxWalkMiles": 3,
  "ovtWeight": 2
 }
} as const;
